### ISSUE TITLE
Rename beneficiary and hide Amount and Units for Wash

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#10]
Request as: 

In Projects sheet we need to:
Change the Conflict IDPs to Conflict IDPs (Recent)
Protracted IDPs to be changed to Conflict IDPs (Prolonged)
Amount and Units to be deleted/Hided
 
In monthly report we need to:
 
Change the Conflict IDPs to Conflict IDPs (Recent)
Protracted IDPs to be changed to Conflict IDPs (Prolonged)
Amount and Units to be deleted/Hided

**Comment by pfitzpaddy** [comment]
Where did the request come from to update the beneficiaries? Hiding units for WASH wont be a problem.

**Comment by drfaustusfade** [comment]
request from wash cluster IMO

**Comment by drfaustusfade** [comment]
[Update: Wash beneficiaries&&Unit hiding](pfitzpaddy/ngm-reportHub#11)
