### ISSUE TITLE
New User Notifications to ORG users

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#100]
Currently, notifications are sent to the first user to organization.
Proposal to update functionality for the system to send notifications to ORG users, and maybe ADMIN
Additionally can be done, functionality for ORG and ADMIN to make/unmake users ORG
Related to: update of users functionality tasks TODO put the link here

**Comment by pfitzpaddy** [comment]
Agreed, this needs review. 

Also, we can review monthly report notifications too - should it be Project Focal point who receives DUE SOON, DUE, OVERDUE notifications only? I think now it is Project Focal point AND location reporter.

I propose 1 sprint before end of 2019 to fix these items (and perhaps a couple more that we can add on), Suggested issues;
1. 1 Organisation per country (multiple sectors)
2. User Roles / Admin Dashboard review
3. Notifications on sign-up / monthly reports
4. Ability to manage ADMIN / ORG roles per organisation in Team page / Profiles
5. Add New Project - lead cluster selectable

This will keep us going for a few months.

A review of taking out the ngm-dashboard-framework / updating dashboard builder and updating Materialize and Angular to 1.7+ is worth looking at too, tho thats potentially a lot of fiddling work for nothing major. I think we need something to last us to Q2 2019 (max) and then transition to a new platform built on Angular2 & microservices. This is for our planning next month.

Links with;
- https://github.com/pfitzpaddy/ngm-reportDesk/issues/98
- https://github.com/pfitzpaddy/ngm-reportDesk/issues/75

**Comment by drfaustusfade** [comment]
the last comment moved to a new issue
