### ISSUE TITLE
Native Queries for Monthly Reports

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#101]
The increase in speed was impressive going to native queries. Its a lot of work but perhaps in the last sprint we can include an update to native queries for get/set [Monthly Reports](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Reports/ReportController.js). This is because some organisations (such as WFP Afghanistan), have a lot of locations per month and it takes an eternity to save. Same goes for native updates to [Projects](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/ProjectController.js).

Along with the items we have outlined for [future sprints](https://github.com/pfitzpaddy/ngm-reportDesk/issues/98), this update could help us squeeze the max out of RH and keep us going for at least 6 months (even 2019) and buy us time to 1) build RH 2.0, 2) migrate countries to new the system.

**Comment by drfaustusfade** [comment]
Also, there were multiple requests already regarding the issue, so it's a good idea to prioritize.
It is a classical bottleneck problem with looping updates over DB, as quite an efficient improvement, it is a comparatively easy task to parallelize not dependent on each other update queries. (e.g. using [async.each function](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/ProjectController.js#L152), note: tricky part might be return values and nested parallelization), that will cut time considerably. 
Setting such parallelization (on local) just for each location loop cuts time for setReport at least third:
![chrome_2018-11-05_18-01-22](https://user-images.githubusercontent.com/29349472/48000999-db5a4a80-e124-11e8-95ab-b7206d6141fc.png)
1(edit)&2(submit) rows no async

![chrome_2018-11-05_18-00-59](https://user-images.githubusercontent.com/29349472/48001003-de553b00-e124-11e8-81f9-05016b596fc9.png)
3(edit)&4(submit) rows async

**Comment by drfaustusfade** [comment]
**Part II: udpate setReport**
https://github.com/pfitzpaddy/ngm-reportEngine/pull/54

**Comment by drfaustusfade** [comment]
Part III: update setReport associations update fix, beneficiaries validation
https://github.com/pfitzpaddy/ngm-reportEngine/pull/58
