### ISSUE TITLE
Next TODO Proposal Nov 18

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#102]
Also, we can review monthly report notifications too - should it be Project Focal point who receives DUE SOON, DUE, OVERDUE notifications only? I think now it is Project Focal point AND location reporter.

I propose 1 sprint before end of 2019 to fix these items (and perhaps a couple more that we can add on), Suggested issues;
1. 1 Organisation per country (multiple sectors)
2. User Roles / Admin Dashboard review
3. Notifications on sign-up / monthly reports
4. Ability to manage ADMIN / ORG roles per organisation in Team page / Profiles
5. Add New Project - lead cluster selectable

This will keep us going for a few months.

A review of taking out the ngm-dashboard-framework / updating dashboard builder and updating Materialize and Angular to 1.7+ is worth looking at too, tho thats potentially a lot of fiddling work for nothing major. I think we need something to last us to Q2 2019 (max) and then transition to a new platform built on Angular2 & microservices. This is for our planning next month.

Links with;
- https://github.com/pfitzpaddy/ngm-reportDesk/issues/98
- https://github.com/pfitzpaddy/ngm-reportDesk/issues/75

_Originally posted by @pfitzpaddy in https://github.com/pfitzpaddy/ngm-reportDesk/issues/100#issuecomment-432932631_

**Comment by drfaustusfade** [comment]
also
6. improve save speed https://github.com/pfitzpaddy/ngm-reportDesk/issues/101

**Comment by drfaustusfade** [comment]
One organization per cluster implementation proposal, RFC

For now there is collection of organizations as admin0/organization/cluster
After update should be admin0/organization

Main points
1. Rename Organization to OrganizationClusters and Create new collection Organization that would include admin0/organization 
2. Compile organizations admin0/organization (Organization) from admin0/organization/cluster(OrganizationClusters) and update OrganizationClusters to contain Organization id, that is one to many relation Organization to OrganizationCluster
3. Update USERs to contain organization_id from new Organization
4. Alternative 1. Add clusters page, after selecting Projects card on Organization, which will have list of organization's clusters (+ n of projects in it, or other total stats), cluster list will come from OrganizationClusters, for adding new cluster - "add cluster" button, that will create new organization_cluster (could be done that multiple clusters are selected on modal e.g. as health/wash tag enabling multicluster projects), selecting cluster will open usual projects page
4. Alternative 2. Use the same projects page as current, add cluster tag in projects rows, add projects will prompt modal for clusters, OrganizationClusters entry will be created if not exists on project save, add clusters filter
4. Note Alt. 1. for listing all project could be added ALL to show all projects and basically the same as Alt.2, Alt.2 is more aligned with current UX design
5. The same as 5 for Stocks, works fine, especially if enabling multicluster, but tricky as idealy there could be one monthly report per organization as there is functionality to select cluster in report

Note: in such a way we get around massive updates with organization ids across db, if merging everything, and relatively clean way to update the system.
Note: changes in path and api updates on backend are implied

**Comment by pfitzpaddy** [comment]
Included in Project no. 7 https://github.com/pfitzpaddy/ngm-reportDesk/projects/7
