### ISSUE TITLE
Add Active Locations to 5W Dashboard

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#103]
A quick win us is for @fakhrihawari to add "Active Locations" on the top row of the 5W dashboard.

![5w_dashboard](https://user-images.githubusercontent.com/1784705/48068542-22f3db80-e1e4-11e8-9e9b-cd9a72aebc37.png)

Any other quick wins for the 5W dashboard?
On the first dashboard we had a couple of charts too http://reporthub.immap.org/desk/#/cluster/health.

**Comment by fakhrihawari** [comment]
pull request link
https://github.com/pfitzpaddy/ngm-reportEngine/pull/48
https://github.com/pfitzpaddy/ngm-reportHub/pull/102

**Comment by drfaustusfade** [comment]
Note: there are in db record with multiple project_titles, and project contact name, probably coming from times when beneficiaries where not updated on project update, that skewed a bit markers count, resaving project, solves the issue. 
TODO check project contacts duplicates/update

**Comment by pfitzpaddy** [comment]
Yes I agree, people see the dashboard and think thats it.
Ideas;
- Sample [link](http://reporthub.immap.org/desk/#/cluster/health/4w), a bit broken
- Sex / Age breakdown (might need a smart way to show this as some countries have boys, girls, men, women, elderly_men, elderly_women)
<img width="489" alt="screen shot 2018-11-07 at 12 27 04 pm" src="https://user-images.githubusercontent.com/1784705/48122398-7e77a500-e288-11e8-88d1-9f58a3c7362a.png">
- Location types, activities, beneficiary types?
<img width="977" alt="locations" src="https://user-images.githubusercontent.com/1784705/48122469-aff07080-e288-11e8-90a0-53a8b6460e59.png">

It should be concise but some additional eye candy would be good. I think the main categories for HPC are organisations (in left menu), locations, activities, populations.

**Comment by pfitzpaddy** [comment]
The other thing is that it can be specific to each sector but that starts to be a bit more of an overhaul. Ideally we can have some high level summary relevant to each country..... a simple sex/age chart is a good start

**Comment by drfaustusfade** [comment]
@fakrihawari 
- [ ] enjoy the highchart donuts as per above
For now, boys/girls and adults men (men+elderly_men)/adults women (women+elderly_women)

**Comment by fakhrihawari** [comment]
![pie](https://user-images.githubusercontent.com/12655589/48190298-f58a6780-e374-11e8-8239-a6442457f927.PNG)

**Comment by pfitzpaddy** [comment]
Yes this looks good - we can go with this, for now. 

Some thoughts;
- Some countries include Elderly Men and Elderly Women, so this layout is still ok but misses that (as a result the numbers wont match).
- There is a full row for "Services to Beneficiaries", maybe we can use this space?
- The Pie charts look great, any ideas on there another way we can represent this information?

**Comment by fakhrihawari** [comment]
![second](https://user-images.githubusercontent.com/12655589/48253572-2b455400-e43a-11e8-9552-691e2e72c120.PNG)

**Comment by pfitzpaddy** [comment]
Looks really good! Lets go with that. Countries that enable elderly include Ethiopia and Nigeria - if you want to do any testing on that (for the engine API). What does it look like when `elderly` at zero?

@fakhrihawari, within this branch, can you please also go ahead and enable `elderly men` and `elderly women` in the monthly reporting forms for Afghanistan.

@drfaustusfade and I will chat to Ahmed and keep him updated on this too!

**Comment by fakhrihawari** [comment]
@pfitzpaddy  okay , for the API I'm not done  yet

**Comment by pfitzpaddy** [comment]
No problem, UI is always the tricky part :)

**Comment by fakhrihawari** [comment]
![wez](https://user-images.githubusercontent.com/12655589/48324211-717cfc00-e662-11e8-948d-09ccfbe25614.PNG)
This when the elderly is zero

**Comment by fakhrihawari** [comment]
pull request link
https://github.com/pfitzpaddy/ngm-reportEngine/pull/49

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD

**Comment by pfitzpaddy** [comment]
Thanks @fakhrihawari, everything is updated. For the ngm-reportEngine, for the chart API you have just created, can you create a new branch that implements this API into native queries? Timur recently converted the dashboard API to native queries and you can see the difference on loading...

**Comment by fakhrihawari** [comment]
okay, i'll try @pfitzpaddy

**Comment by fakhrihawari** [comment]
this pull request for native queries
https://github.com/pfitzpaddy/ngm-reportEngine/pull/50

**Comment by pfitzpaddy** [comment]
Great, that is updated.

**Comment by drfaustusfade** [comment]
@fakhrihawari could you also try group and sum clause in the query if speed is not sufficient.

**Comment by fakhrihawari** [comment]
update API to make it more faster
pull request 
 https://github.com/pfitzpaddy/ngm-reportEngine/pull/51

**Comment by drfaustusfade** [comment]
Nice, can you please also try to document this component api/ui, in free form (gitbook, gitpages etc), that would be a good practice for us, additionally to explore possible parameters.

**Comment by drfaustusfade** [comment]
No, I don’t, we need to come up with the most practical way, try it in free form, check on the web web or react components docs style guides for ui, for api it’s pretty standard everywhere (like swagger or check gitbook way), we will review after.

**Comment by fakhrihawari** [comment]
Do we put it on this one https://reporthub.gitbook.io, or we can make a new one?
