### ISSUE TITLE
Discussion: photo attachments for monthly reports

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#106]
user story: as a user to attach photos for the monthly report, enabling centralized storage
it may be better to implement and store in external services, with referencing, tagging and filtering

**Comment by pfitzpaddy** [comment]
Lets add this one to our final sprint of the year

**Comment by pfitzpaddy** [comment]
Add to sprint 7 https://github.com/pfitzpaddy/ngm-reportDesk/issues/134
