### ISSUE TITLE
Review: pdf download 

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#107]
- [x] needs to be fixed as for now returns a blank page
- [x] improve speed

**Comment by drfaustusfade** [comment]
fix: https://github.com/pfitzpaddy/ngm-reportHub/pull/109

**Comment by drfaustusfade** [comment]
possible improvement https://github.com/pfitzpaddy/ngm-reportPrint/pull/1

**Comment by pfitzpaddy** [comment]
Merged

**Comment by drfaustusfade** [comment]
- [ ] fix for dashboards which require admin lists
- [ ] fix when filtered to cluster doesnt return filtered to cluster pdf ( possible user roles issue on dashboard )
- [ ] phantomjs loads all resourses for each request, research how to optimize it
- [ ] research other tools for snapshots

**Comment by pfitzpaddy** [comment]
PDF download creates empty PDF, most likely related to ADMIN roles
