### ISSUE TITLE
Update PROD: latest async lib

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#109]
for latest async.eachOfLimit function which will be used for parallelization

to run in ngm-reportEngine
```
cd /home/ubuntu/nginx/www/ngm-reportEngine
npm install async --save
```

**Comment by drfaustusfade** [comment]
**After update to use it**: dissable built in async and import var async = require('async'); in files

**Comment by pfitzpaddy** [comment]
Merged https://github.com/pfitzpaddy/ngm-reportEngine/pull/53
