### ISSUE TITLE
Update WASH beneficiary types for AFG in db

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#11]
We have made an update to 'beneficiary_type_name' in the FE. Changes now need to be applied to the db

**Comment by pfitzpaddy** [comment]
This can be done via a db update patch as below. Once updated please backup the PROD and place on Dropbox folder

```
// update beneficiary_type_name
update({ ‘admin0pcode’ : ‘AF’, cluster_id: 'wash' , beneficiary_type_id: 'idp_conflict’} , { $set: { beneficiary_type_name: 'Conflict IDPs (Recent)' } });

```

**Comment by drfaustusfade** [comment]
Patch applicable to beneficiaries collection, shall we leave out others ( project, report etc ) which have  _beneficiary_type_ field with _beneficiary_type_id_ and  _beneficiary_type_name_? Is that field in use somewhere at all?

**Comment by pfitzpaddy** [comment]
from the top of my head I think _beneficiary_type_ is a legacy attribute or it is an array that is used to store all activities for a project in the project, report and beneficiaries. I thought i was being smart to store it for potentially filtering, but its obsolete. Only _beneficiary_type_id_ and _beneficiary_type_name_ are relevant on _targetbeneficiaries_ and _beneficiaries_ table

**Comment by drfaustusfade** [comment]
Ok, it's clear now. I will update.
Queries for reference:
```javascript 
db.beneficiaries.update({ 'admin0pcode' : 'AF', cluster_id: 'wash' , beneficiary_type_id: 'idp_conflict'} , { $set: { beneficiary_type_name: 'Conflict IDPs (Recent)' } }, { multi:true });
db.targetbeneficiaries.update({ 'admin0pcode' : 'AF', cluster_id: 'wash' , beneficiary_type_id: 'idp_conflict'} , { $set: { beneficiary_type_name: 'Conflict IDPs (Recent)' } }, { multi:true });
db.beneficiaries.update({ 'admin0pcode' : 'AF', cluster_id: 'wash' , beneficiary_type_id: 'idp_protracted'} , { $set: { beneficiary_type_name: 'Conflict IDPs (Prolonged)' } }, { multi:true });
db.targetbeneficiaries.update({ 'admin0pcode' : 'AF', cluster_id: 'wash' , beneficiary_type_id: 'idp_protracted'} , { $set: { beneficiary_type_name: 'Conflict IDPs (Prolonged)' } } , { multi:true });
```

**Comment by drfaustusfade** [comment]
updated, last backup on dropbox.
