### ISSUE TITLE
Update: activities and beneficiary types for UNICEF

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#112]
- [x] fix duplication subactivity issue, be having unique subactivities per country ( _emergency and _mch ) 
- [x] add IDPs and Chronic Emergency beneficiary types

**Comment by drfaustusfade** [comment]
fe update https://github.com/pfitzpaddy/ngm-reportHub/pull/110

**Comment by pfitzpaddy** [comment]
Merged
