### ISSUE TITLE
5W Chart Breakdown - incorrect rendering

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#115]
In the 5W dashboard, it looks as tho the colours are correct (blue on the left for male, pink on the right for female), but that the percentages are incorrect.

<img width="340" alt="chart_render" src="https://user-images.githubusercontent.com/1784705/49214924-47a73180-f3e5-11e8-9250-0d34658e9c26.png">

There is a mix up in there somewhere

**Comment by pfitzpaddy** [comment]
Unless of course the chart is correct and the percentages are not! :)

**Comment by fakhrihawari** [comment]
ok will fix it

**Comment by fakhrihawari** [comment]
![fix](https://user-images.githubusercontent.com/12655589/49217882-6fa48e00-f401-11e8-864c-b11f293b4149.PNG)

**Comment by fakhrihawari** [comment]
I'm putting data in the wrong place

**Comment by pfitzpaddy** [comment]
Fixed https://github.com/pfitzpaddy/ngm-reportEngine/pull/56
