### ISSUE TITLE
CASH Reporting UPDATES

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#117]
- [x] (1) remove activity type “Cash/Voucher” 
- [x] (2) units for _cash_ _Delivery_ only USD and AFN
- [x] (3) rename Cash Voucher Working Group to MPC in all data, old data propagation issue
- [ ] (4) request ```Filtering for partner’s cash or voucher data should be based on the “Activity”, “Description” and “Delivery” tabs, so that whenever Cash or Voucher is reported under different clusters, the extract captures them.``` that is add _Delivery_ _Cash_ and _Voucher_ into filtering, 
- [x] (5) new _Mechanism_ field, for _Cash_ (select:Hawala, Cash in Envelope, Mobile Cash, Bank, Electronic Card) or _Voucher_(select:Paper Voucher, Mobile Voucher, Electronic Card Voucher) _Delivery_ (NOTE: requires db update script, as as all data currently in _Delivery_ field (FSAC and MPC _Delivery_ values should be migrated to _Mechanism_, with _Delivery_ set as above )
- [x] (6) db update script for 5

**Comment by drfaustusfade** [comment]
@fakhrihawari please work on 2 and 5

**Comment by drfaustusfade** [comment]
There will be two fields from one, the script will update both, based on values in it. It can be both ways. Delivery: cash, voucher, in-kind.

**Comment by fakhrihawari** [comment]
pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/120
https://github.com/pfitzpaddy/ngm-reportEngine/pull/64

**Comment by drfaustusfade** [comment]
```
// for collections where "cluster" is not "MPC"
db.getCollection("budgetprogress").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
db.getCollection("beneficiaries").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
db.getCollection("location").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
db.getCollection("targetlocation").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
db.getCollection("stocklocation").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
db.getCollection("stockreport").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
db.getCollection("stockwarehouse").update({"admin0pcode" : "AF", cluster_id:"cvwg", cluster: {$ne: "MPC"}}, { $set: { cluster: "MPC" } }, { multi:true });
```

**Comment by drfaustusfade** [comment]
- [ ] only AFG and USD units also for other clusters, cash activities

**Comment by fakhrihawari** [comment]
Pull Request link
https://github.com/pfitzpaddy/ngm-reportHub/pull/136

**Comment by drfaustusfade** [comment]
- [x] fix broken functionality due to form processing by fields configuration updates

**Comment by pfitzpaddy** [comment]
Thanks for these updates, taking a look at the pull request now. FYI - if you see the activities for Child Protection, the list is in the `unit_activity_id` column (i.e. `ngmClusterBeneficiaries.form.active[ $locationIndex ].columns[ 'unit_type_id' ]`). Moving forward lets transfer all lists into the `unity_activity_id` column. To update the activities.csv there is also a couple of extra lines (to convert the CSV JSON into JSON, in the same way;
```
mongoimport -d ngmHealthCluster -c activities --drop --headerline --type csv --file /home/ubuntu/data/csv/activities.csv
mongo
use ngmHealthCluster
db.getCollection('activities').find({activity_type_id:'hardware_materials_distribution'}).forEach(function (d) { if( d.kit_details.length ) { d.kit_details = JSON.parse(d.kit_details); db.getCollection('activities').save(d); } });
db.getCollection('activities').find({}).forEach(function (d) { if( d.unit_type_id.length ) { d.unit_type_id = JSON.parse(d.unit_type_id); db.getCollection('activities').save(d); } });
exit

```

**Comment by drfaustusfade** [comment]
nice, no need for excess processing for activities with specific units ( looks like most of them, to review ), 
also as info though if put all possible as per now, not including currencies units (52)  into one row it is +~3kb per row, or +~60b per unit in activity list config

**Comment by pfitzpaddy** [comment]
That is a very good point. We will keep an eye on it. I was thinking that the lists would be much smaller and then only country specific activities are filtered so that should reduce size, definitely something to look at tho.

**Comment by pfitzpaddy** [comment]
@drfaustusfade, number 4 an interesting one here. (status: not important, not urgent)

**Comment by pfitzpaddy** [comment]
Made it a seperate issue here https://github.com/pfitzpaddy/ngm-reportDesk/issues/218. This would require a few changes at activities.csv, ngm-reportEngine, ngm-reportHub and some db updates - so a large task something thats already working (if it aint broke dont fix it :) ). Something we can consider in the future...
