### ISSUE TITLE
Chart Widget - Bug on Zero

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#118]
Minor issue, Highcharts seems to fail when chart widget is 0 (elderly men, elderly women). Should have a check for this or default structure when zero should not display error.

<img width="1067" alt="screen shot 2018-12-02 at 9 17 47 am" src="https://user-images.githubusercontent.com/1784705/49353565-1035cf00-f6dc-11e8-9c2f-0fc38b4bd303.png">

**Comment by pfitzpaddy** [comment]
Looks as tho it could be an issue from the API, Ethiopia will have elderly and the chart is returning zero

<img width="974" alt="screen shot 2018-12-04 at 7 05 33 pm" src="https://user-images.githubusercontent.com/1784705/49449065-b4606880-f7f7-11e8-8326-5b4cd94424a1.png">

**Comment by pfitzpaddy** [comment]
In fact, for Ethiopia there is no elderly population, so this is correct, however the console bug for highcharts library remains... must be a bad format somewhere

**Comment by fakhrihawari** [comment]
it missing variable data  ,so it cannot push because the variable not defined,
link pull request : https://github.com/pfitzpaddy/ngm-reportHub/pull/116

**Comment by pfitzpaddy** [comment]
Merged
