### ISSUE TITLE
Update db project collection / reports to display correctly on PowerBi

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#12]
ReportHub beneficiary data is available as CSV via an API linked to PowerQuery, which is used in PowerBi. Currently records exist that cause duplications, these need to be updated.

**Comment by pfitzpaddy** [comment]
So Michele has the following issue

> 
> IMC submitted their monthly report for September and that spelling issue is back causing two categories display instead of one.
> 
> they managed somehow to use the activity "Health Education, Training &  Awareness" with double space after the & while the others are using "Health Education, Training & Awareness" which has only one space after the & The error is only in September, project_id 58b0a31f2593c1e07739e46c
> 
> The other duplicating category issue is in Stocks
> we have both stock item "Health: miscellaneous" and just "Miscellaneous"
> If you can merge them, unless they are in fact two different things...in that case pass me stock item definitions so that I make a legend
>

**Comment by pfitzpaddy** [comment]
And please just comment if any of this dosnt make any sense...

**Comment by drfaustusfade** [comment]
Issue fixed, there was double spacing in project definition details under activity type
 as _activity_type_name:"Health Education, Training &__Awareness"_, so that it propagated to reports, resaving project details and resubmitting affected reports was a solution.
The unclear question still is how it came that starting from September only, as it is coming directly from activity collection.

**Comment by pfitzpaddy** [comment]
Touche'. So this was 'fixed' last month, looks like one or 2 were missed. Nice work!

**Comment by pfitzpaddy** [comment]
Can you confirm with Michele he is happy?

**Comment by drfaustusfade** [comment]
There is one more with stocks:
"Health: miscellaneous" and just "Miscellaneous"
There is no miscellaneous stock type item anymore in stockitems collection
![excel_2017-11-08_14-39-28](https://user-images.githubusercontent.com/29349472/32543374-0f9428a2-c493-11e7-9bb1-eb23e584bba6.png)
Entries dated back to jan and feb, that is an artifact.

We can update stock db, there is only 4 entries for health: 
db.stock.update({stock_item_type: "miscellaneous"}, {$set:{ stock_item_type:"health_miscellaneous", stock_item_name:"Health: Miscellaneous"}}, {multi:true} )

**Comment by drfaustusfade** [comment]
Updated.
