### ISSUE TITLE
Update: add NG to admin dashboard filter

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#125]
- [x] add Nigeria to country filter on admin dashboard
- [x] region/country menu functionality the same as of cluster dashboard

@pfitzpaddy Also on cluster dashboard, SUPERADMIN country filter is based on region, but on admin dashboard they are independent, shall we make them consistent, or there is a reason

**Comment by pfitzpaddy** [comment]
@drfaustusfade, if we can fix the Admin dashboard in the process to be the same as 5w (filter country menu based on region menu), that would be great.

**Comment by fakhrihawari** [comment]
Pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/118

**Comment by pfitzpaddy** [comment]
Merged
