### ISSUE TITLE
Proposal: additional activities field: fields

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#126]
it will allow setting fields to report on from configuration,
options to include could be: default value, required field, constraint
e.g. a case for cash related activities, specifying _delivery_ would show and enable this field by checking of existence of it on activity record of fields property
that could possibly remove the need to do it on frontend and enabling admin configuration on ui

**Comment by pfitzpaddy** [comment]
activities.csv in some ways meets this discussion
