### ISSUE TITLE
2) Epic: ReportHub User Roles

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#128]
Currently there are USER, ORG, ADMIN and SUPERADMIN user roles. They need to be updated with respective functionality implemented on the UI as follows;

### User Roles
- User Roles defined below with DEFAULTS.
- User Access (READ, WRITE) capabilities should be updated by respective ADMIN and can be set on each of the User Roles described below.
- User Access / Roles should be updatable from PROFILE page and TEAM page (in the table)
- Updating Roles / Access from a button in the table will open a modal with the Roles / Access options.
- Profile page should have "Back to Team" button
- Requires updates to PROFILE page, PROJECT DETAILs, REPORTs. 

**USER**
- PROJECTS: READ for own Org / WRITE for own Org
- USERs: READ for own Org
- ADMIN Dashboard: $filter=[ admin0pcode, Organization ], 
- ADMIN MENU: [ Sector, Report ]

**ORG**
- PROJECTS: READ for own Org / WRITE for own Org
- USERs: READ for own Org / WRITE for own Org (Add, Edit, Delete, Roles)
- ADMIN Dashboard: $filter=[ admin0pcode, Organization ], 
- ADMIN MENU: [ Sector, Report ]

**CLUSTER**
- PROJECTS: READ for own Cluster / WRITE for own Cluster
- USERs: READ for own Cluster / WRITE for own Cluster (Add, Edit, Delete, Roles)
- ADMIN Dashboard: $filter=[ admin0pcode, Cluster ], 
- ADMIN MENU: [ Report, Organization ]

**COUNTRY**
- PROJECTS: READ for own Country
- USERs: READ for own Country
- ADMIN Dashboard: $filter=[ admin0pcode ], 
- ADMIN MENU: [ Cluster, Report, Organization ]

**REGION ORG**
- PROJECTS: READ for own Region
- USERs: READ for own Region
- ADMIN Dashboard: $filter=[ adminRpcode, Organization ], 
- ADMIN MENU: [ Country, Cluster, Report ]

**REGION**
- PROJECTS: READ for own Region
- USERs: READ for own Region
- ADMIN Dashboard: $filter=[ adminRpcode ], 
- ADMIN MENU: [ Country, Cluster, Report, Organization ]

**HQ ORG**
- PROJECTS: READ for own All
- USERs: READ for own All
- ADMIN Dashboard: $filter=[ all, Organisation ], 
- ADMIN MENU: [ Region, Country, Cluster, Report ]

**HQ**
- PROJECTS: READ for own All
- USERs: READ for own All
- ADMIN Dashboard: $filter=[ all ], 
- ADMIN MENU: [ Region, Country, Cluster, Report, Organization ]

**Comment by pfitzpaddy** [comment]
Looking good. Before we close this one, we should update the account type to be a TITLE and small DESCRIPTION of each User Access account (and then we wont need to display ORG, USER, REGION etc). I will put something together on the flight around a title and description and post here. Great work.

**Comment by pfitzpaddy** [comment]
Quick notes: with the following user roles;
`    "roles" : [ 
        "USER", 
        "ORG", 
        "ADMIN", 
        "COUNTRY", 
        "REGION"
    ],`

I was unable to update User to COUNTRY or to REGION.

**Comment by fakhrihawari** [comment]
Yes because the higher user level is region and i check in the ngmAuthentication.js we not add or set "EDIT_USER_ROLE" in the role region

**Comment by pfitzpaddy** [comment]
Yes, you are right thats correct. Will do a review on what we should implement as I agree with REGION, but perhaps REGION should be able to set COUNTRY and COUNTRY should also be able to set COUNTRY. Nice work

**Comment by fakhrihawari** [comment]
![edit](https://user-images.githubusercontent.com/12655589/51099831-8c582200-1805-11e9-9113-d0c0477bb314.PNG)

**Comment by pfitzpaddy** [comment]
@drfaustusfade can you take a quick look at this one (or confirm), looks as tho I can simple update the list in EDIT_RESTRICTED in `ngmPermissions`. Does this just affect ability to update User Roles or is it also related to forms? I want Users to be able to update User Roles at their level (i.e. Country can update to Country, etc)

**Comment by drfaustusfade** [comment]
EDIT_RESTRICTED is related to editing forms
EDIT_USER_RESTRICTED is related to user editing
```
// for Country then should be like that
EDIT_USER: true,   // can edit user permission
EDIT_USER_ROLES: [ 'USER', 'COUNTRY' ],   // roles which can be edited
EDIT_USER_RESTRICTED: ['admin0pcode', 'adminRpcode'],   // if these match to users, that can edit this user 
```

**Comment by pfitzpaddy** [comment]
@fakhrihawari, can you please make the follow updates on User Roles when possible;
- When a User Role is ORG or above, `app_home` gets set to `/cluster/admin/`
- When a User Role is USER only, `app_home` gets set to `/cluster/organization/`
- In User Profile, place ROLES Card above CONTACT Card
<img width="684" alt="rh_profile" src="https://user-images.githubusercontent.com/1784705/52030758-7eafd580-2543-11e9-85e2-d0b73448b39f.png">
- Sort Team table by Updated by default
<img width="937" alt="rh_sort_updated" src="https://user-images.githubusercontent.com/1784705/52030984-6a200d00-2544-11e9-9a1c-76d955b7012f.png">

**Comment by pfitzpaddy** [comment]
Descriptions for User Roles
USER
- The USER can add, edit and update reports for your Organization
ORG
- The ORG role is to manage the USERS of your Organization
CLUSTER
- The CLUSTER role is to manage the partners and projects of your Sector
COUNTRY
- The COUNTRY role acts as an observer and can view (but not edit) all Sectors
REGION_ORG
- The REGION_ORG role can view projects in your Region for your Organization
REGION
- The REGION_ORG role can view projects in your Region for all Sectors
HQ_ORG
- The HQ_ORG role can view projects Globally for your Organisation
HQ
- The HQ role can view projects Globally for your all Sectors
SUPERADMIN
- Beware, here be dragons!

**Comment by pfitzpaddy** [comment]
These requests are now updated

**Comment by pfitzpaddy** [comment]
Re-opening this one, it would be great if we can change the COUNTRY and CLUSTER of the user, from the PROFILE page

**Comment by fakhrihawari** [comment]
Pull Request for 'change the COUNTRY and CLUSTER of the user, from the PROFILE page'
https://github.com/pfitzpaddy/ngm-reportHub/pull/151

**Comment by pfitzpaddy** [comment]
Nice work guys
