### ISSUE TITLE
FSAC AF: 2019 updates

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#136]
In discussion
Requested to develop functionality, for future two activities
- off location activity reporting for call centre activity
- additional baseline HHs and auto-field percentage increase fields for HH monitoring activity

**Comment by drfaustusfade** [comment]
290119 meeting #TODO elaborate on having details
- [ ] add food consumption score reporting (4 groups/columns that sum to 100%)
- [x] upload/download assessments reports (docs and pictures) to projects (not monthly reports): we can add on the project page _Documents_ card;
- [x] add indicator selection column ( not 1activity to 1indicator mapping! ) ::first; and calculations ::add later
- [x] update activities and beneficiaries, SO the same as the previous year

**Comment by pfitzpaddy** [comment]
3rd point quite an interesting one.....

**Comment by drfaustusfade** [comment]
need some updates as indicators for af fsac are dependent on _beneficiary_type_ selection
for example _# of conflict affected IDPs women, men and children of all ages who receive adequate in-kind responses, in a timely manner._ depends on   _Conflict Affected IDPs_	and if __in_kind_ subactivities of Food Assistance

Indicator selection cases:
for Food Assisance activity depends if sub activity cash or in_kind and beneficiary_type
for Livelihood activity depends on beneficiary_type
and 1 activity independent of beneficiary_type

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportEngine/pull/71

**Comment by drfaustusfade** [comment]
updated https://github.com/pfitzpaddy/ngm-reportHub/pull/147
