### ISSUE TITLE
Update: af drought dashboard include non emergency drought activities

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#138]
WFP requested to include into dashboard filter with non-emergency drought activities
Natural Disaster Affected (Drought)
- [x] add filter Response Type [ all, default: emergency, non emergecy ], Population type [response filter > all: add Natural Disaster, response filter > non emergency: Natural Disaster ], update backend filtering

**Comment by fakhrihawari** [comment]
So the population filter based on response type?

**Comment by fakhrihawari** [comment]
Pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/123
https://github.com/pfitzpaddy/ngm-reportEngine/pull/65

**Comment by pfitzpaddy** [comment]
Merged

**Comment by drfaustusfade** [comment]
- [ ] fix links ![chrome_2018-12-24_17-27-48](https://user-images.githubusercontent.com/29349472/50400042-49280780-07a1-11e9-81e2-ba6cd6cb49b9.png)

**Comment by fakhrihawari** [comment]
pull request for fix link:
https://github.com/pfitzpaddy/ngm-reportHub/pull/124
