### ISSUE TITLE
Update Cluster Locations Map

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#14]
Currently the dashboard Locations map is displaying one location per project when in fact its possible multiple locations might exist per project.

**Comment by pfitzpaddy** [comment]
So essentially I have a project with a report with several locations. If you register to `Ethiopia | WHO | Health` you will see the project / reports.

<img width="1056" alt="screen shot 2017-11-08 at 12 03 24 am" src="https://user-images.githubusercontent.com/1784705/32517716-4ca427cc-c418-11e7-89d1-0e7410c64258.png">

But for some reason only the one location is displayed on Locations in the dashboard.

<img width="1059" alt="screen shot 2017-11-08 at 12 05 25 am" src="https://user-images.githubusercontent.com/1784705/32517795-8e0fa966-c418-11e7-92b4-14ce1a91b2c5.png">

This issue will most likely be somewhere in [here](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Dashboards/ClusterDashboardController.js#L857) 

The WHO Ethiopia example is a good one because there is not so much data to get through. But that map should be displaying 3 locations, as the project has 3 target locations. Happy hunting

**Comment by drfaustusfade** [comment]
the bug is in https://github.com/pfitzpaddy/ngm-reportHub/blob/8c353bc51a767220c38ddeb450ba9aa5f9d37d9d/app/scripts/modules/cluster/reports/forms/cluster.project.form.details.js#L654
Function copies _facility_lng_ and _facility_lat_ from the last record, it needs to be null.

On the backend, markers are taken from _beneficiaries_ collection, based on the uniqueness of project, lng, and lat, so at least one record should exist for a targetlocation.

**Comment by drfaustusfade** [comment]
on [pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/16)

```javascript
\\ db could be updated with

db.beneficiaries.find({"admin0pcode" : "ET","organization" : "WHO"}).forEach(

    function ( row ) {
      if ( row.admin3lat && row.admin3lng ) {
        row.facility_lat = row.admin3lat;
        row.facility_lng = row.admin3lng;
      } else {
        row.facility_lat = row.admin2lat;
        row.facility_lng = row.admin2lng;
      }
            
     db.beneficiaries.save( row );
    }
  );

db.targetlocation.find({"admin0pcode" : "ET","organization" : "WHO"}).forEach(

    function ( row ) {
      if ( row.admin3lat && row.admin3lng ) {
        row.facility_lat = row.admin3lat;
        row.facility_lng = row.admin3lng;
      } else {
        row.facility_lat = row.admin2lat;
        row.facility_lng = row.admin2lng;
      }
            
     db.targetlocation.save( row );
    }
  );

```

**Comment by drfaustusfade** [comment]
![2017-11-22_10-37-51](https://user-images.githubusercontent.com/29349472/33114082-d0067500-cf78-11e7-8299-f3c62e5986d8.gif)
fixing showing markers if multiple facilities per location.
[pull request](https://github.com/pfitzpaddy/ngm-reportEngine/pull/9)
