### ISSUE TITLE
Issue with monthly generated reports

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#15]
Reports are possibly being generated past project end dates. I say possibly as there were some recent changes and experiments with reports. We need to understand what the issue is and fix it

**Comment by pfitzpaddy** [comment]
Ok my bad, this is not an issue. The project end date is 30 Aug, 2018, so the system is correct

**Comment by drfaustusfade** [comment]
Update db project collection / reports to display correctly on PowerBi #12
Solving above issue We activated project, made changes and marked as completed again.
But we have where( { project_end_date: { $gte: moment().startOf( 'M' ).format( 'YYYY-MM-DD' ) } } ) constraint on BE.

**Comment by pfitzpaddy** [comment]
Ok I think I understand that. So you used the ReportHub interface to updated and did not run a db update? Thats totally fine and actually thats safer too!

**Comment by pfitzpaddy** [comment]
Although this issue was related to monthly reports getting generated after the Project End Date (but thats not the case, since i was seeing 2017 when it is actually Project End Date of 2018 - so the system is fine). The user has been updated to correct the Project End Date of the project
