### ISSUE TITLE
Update Project Contact

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#16]
There is a request to update project contact:
Details and query attached:
[UPDATE_PROJECT_CONTACT_DATA.txt](https://github.com/pfitzpaddy/ngm-reportDesk/files/1453562/UPDATE_PROJECT_CONTACT_DATA.txt)

fields to update: email, username, name, position, phone, 
in collections: project, report, targetbeneficiaries, targetlocation, budgetprogress, location

**Comment by drfaustusfade** [comment]
they also asking to have multiple focal points to a project, proposal to add to agenda such functionality.

I also did as an experiment project contact details form as below, for now it can do updates as in request above: 
![chrome_2017-11-08_16-09-47](https://user-images.githubusercontent.com/29349472/32547323-8db2be40-c49f-11e7-9013-4eadd8b50b57.png)

Can put it on github later.

**Comment by pfitzpaddy** [comment]
Yes please add this to GitHub as a pull request and ill merge it into a branch to take a look. A couple of thoughts, I think it works there as last element before saving, but what do you think about it at the top (not a request!)? This is a great start, I think its going to lead to something thats a real missing link in the ReportHub system! Great work.

**Comment by pfitzpaddy** [comment]
I think where it is does work best - but also im thinking along the lines of users finding it for an update of project focal point, if its at the top its very obvious?

**Comment by drfaustusfade** [comment]
agree on top would be logically sound, I put it down then not to scroll all the time to save =)

check this out, selecting from the list of organization users.
![2017-11-23_00-52-47](https://user-images.githubusercontent.com/29349472/33148827-feafc09c-cfea-11e7-97a9-ed50c5804399.gif)

<<<<<on [pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/17)<<<<<<

**Comment by drfaustusfade** [comment]
done on [pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/26)
