### ISSUE TITLE
Make side menu collapsable

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#164]
Have collapsable functionality (web and mobile)

**Comment by pfitzpaddy** [comment]
i.e. https://materializecss.com/sidenav.html.
Minimize toggle could be located next to title?
![ReportHub_minimize](https://user-images.githubusercontent.com/1784705/65386968-d2d22900-dd63-11e9-9450-8e8cafa042e8.png)

**Comment by fakhrihawari** [comment]
First attempt
![NkBadkoD8h](https://user-images.githubusercontent.com/12655589/65417005-4e46df80-de23-11e9-89d9-5b33a827c6e0.gif)

The button should next to title?

**Comment by drfaustusfade** [comment]
should dashboard expand to additional space?
using hamburger on dashboard negative space next to title feels a bit crowded
as there is no header container also what if to explore to in-menu toggle
like
![chrome_2019-09-23_22-09-30](https://user-images.githubusercontent.com/29349472/65449057-6c2a3980-de4f-11e9-8639-0fa3501ab285.png)
![chrome_2019-09-23_22-09-47](https://user-images.githubusercontent.com/29349472/65449098-7f3d0980-de4f-11e9-85d5-78d9cff6bdc8.png)
but that would work better for default closed menu

and if using hamburger maybe a change in the user menu to arrow-down?

**Comment by pfitzpaddy** [comment]
Thanks Fakhri, a nice first shot. Yes, we will need the `<div class="container">` to expand too.

For the hamburger, I think next to the title is ok (for now). Im thinking of re-skinning the header, title, subtitle and downloads section to something like this.... https://developers.google.com/web/tools. We can then also take a look at that side menu too.

**Comment by pfitzpaddy** [comment]
Not sure how I feel about this, but it might also be an option?
![menu](https://user-images.githubusercontent.com/1784705/65481143-12a92580-deb6-11e9-84bf-35f68da1d0c7.png)

**Comment by pfitzpaddy** [comment]
Or make them both blue, but the hamburger is not a button (or the hamburger is a flat button..)

**Comment by pfitzpaddy** [comment]
I also agree @drfaustusfade that we will need that slim menu running the height of the screen to host the hamburger button for menu expansion.

**Comment by fakhrihawari** [comment]
![UmRpD9hmeB](https://user-images.githubusercontent.com/12655589/65481922-800e8380-dec1-11e9-8847-65962387d8b7.gif)

**Comment by pfitzpaddy** [comment]
Final for this I recommend;

1. Menu dropdown button becomes dropdown icon ( v )
2. Menu dropdown moves to left of screen
3. Menu contents become left aligned
4. username becomes left aligned to dropdown button
5. Current dropdown button becomes the minimize button
6. Current dropdown button becomes flat button or simple icon (no z-index)
7. Menu when minimized remains on screen as strip running height of screen
![65449098-7f3d0980-de4f-11e9-85d5-78d9cff6bdc8](https://user-images.githubusercontent.com/1784705/65660676-38b6fd00-e051-11e9-9c87-5cb97d83758f.png)
8. <div="container"> expands to fill empty space

**Comment by fakhrihawari** [comment]
![t1BAO8SmpC](https://user-images.githubusercontent.com/12655589/65680351-f7d6dc80-e080-11e9-89a8-16aec747d25e.gif)

**Comment by pfitzpaddy** [comment]
Almost there, everything as you have it, with the menu hamburger to be in the following position (and "Menu" text not required);
![65481143-12a92580-deb6-11e9-84bf-35f68da1d0c7](https://user-images.githubusercontent.com/1784705/65680571-08835480-e079-11e9-836d-12fa7f6ad9e9.png)
And then the `<div="container">` to expand

**Comment by fakhrihawari** [comment]
![MBsPnpR7Jl](https://user-images.githubusercontent.com/12655589/65743015-f3f89800-e11c-11e9-96b2-d8d33aa54c6f.gif)

**Comment by pfitzpaddy** [comment]
That’s looking good, I suggest we make the collapse icon an icon, not a button when the side menu is expanded. Also, for the container, it should expand. After that it’s good to go.

**Comment by fakhrihawari** [comment]
![button](https://user-images.githubusercontent.com/12655589/65749668-c1f13100-e130-11e9-8375-9f4400754f0c.PNG)
so like this?

**Comment by pfitzpaddy** [comment]
Yes, that’s it. Thanks

**Comment by fakhrihawari** [comment]
![yuLf7CFmFN](https://user-images.githubusercontent.com/12655589/65849103-21d71a00-e373-11e9-9c45-546b9ff2e46a.gif)
So like this? or need more expand?

**Comment by pfitzpaddy** [comment]
That looks great.

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/305

**Comment by pfitzpaddy** [comment]
Merged. Some issues on expansion as below;
1. Menu is closed on initial opening of page (it should be open by default) (see below)
2. When Menu is closed, the container is not aligned correctly (see below)
![ReportHub_menu_closed](https://user-images.githubusercontent.com/1784705/65960264-ebce8e80-e475-11e9-8b9e-6041574f95ed.png)
3. When Menu is open, container is ok.
![ReportHub_menu_open](https://user-images.githubusercontent.com/1784705/65960799-1836da80-e477-11e9-9317-f4d30caaffcc.png)

**Comment by fakhrihawari** [comment]
Ok , i will fix it

**Comment by fakhrihawari** [comment]
Link Pull request for fix:
https://github.com/pfitzpaddy/ngm-reportHub/pull/306

**Comment by pfitzpaddy** [comment]
Merged
