### ISSUE TITLE
Targets Follow Same Structure as Monthly Progress Reports

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#166]
There has been a request to combine adding Target Locations with Target Populations in the Project Plan. This would require some discussion with AFG and cluster partners / users.

Im wondering if they would be up open for this idea and it it makes sense? From memory, Afghanistan projects have Population and Location targets separately. It would make planned vs actual a lot easier. Otherwise it might be a country by country approach, could get ugly....

![reporthub-plan](https://user-images.githubusercontent.com/1784705/52519679-5e8dbe00-2c89-11e9-9fc4-a77e3129daea.png)

**Comment by drfaustusfade** [comment]
That is definitely a friendlier ux, the concern to inquire from partners is if they on project creation know totals by location, or just total for the project, because totals by location can complicate reporting planned numbers in the latter case, but from another side more granular planning, and comparison

**Comment by pfitzpaddy** [comment]
Yes you got the point exactly.... I think for now we can park it but something we should raise to gauge potential sometime in the future. Nigeria also said the way it is now (Targets separated) is how they do it, so in fact its the response plan that could be improved, since RH just mimics that requirement. But certainly it would make our lives easier from a monitoring (planned vs targets) point of view in the perfect world...

**Comment by pfitzpaddy** [comment]
This does not follow the current HRP structure. One approach is to have monthly planned and monthly actual (most likely as cards and seperate forms, with planned beneficiary entries stored in a new collection). This would not necessarily double the amount of work for users, since they could "copy last month" or "copy plan" and would actually provide the ability to compare location by location planned vs. actual. Closing this until it becomes a relevant issue (WASH Nigeria where interested in such a solution).
