### ISSUE TITLE
Place Project Documents in Project Plan

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#182]
No need for an extra card within Project Summary, we can place the Project Documents card inside the Project Plan.

![ReportHub-documents](https://user-images.githubusercontent.com/1784705/54785846-42206200-4bf5-11e9-8719-4731a2f8f65c.png)

Please make it HIDDEN on NEW PROJECT! Otherwise Partners will get confused...

**Comment by fakhrihawari** [comment]
![mock-upinnew](https://user-images.githubusercontent.com/12655589/54799494-2027ed80-4c90-11e9-87fe-f5b36c987c8b.PNG)

**Comment by fakhrihawari** [comment]
To upload project document  need project_id , if new project how we handle it? hide the upload  if it's new project? or ?

**Comment by drfaustusfade** [comment]
Yes, it should be hidden.

**Comment by fakhrihawari** [comment]
Link for pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/159
