### ISSUE TITLE
Proposal design for translate menu

### ISSUE THREAD

**Issue by fakhrihawari** [pfitzpaddy/ngm-reportDesk#184]
![pptrnslat](https://user-images.githubusercontent.com/12655589/55055608-15a59380-5096-11e9-90e3-eb53e2cabc1d.PNG)

**Comment by fakhrihawari** [comment]
![4Q4YjUzkB0](https://user-images.githubusercontent.com/12655589/55055899-17bc2200-5097-11e9-9ded-74141e6c6038.gif)
Design menu language

**Comment by drfaustusfade** [comment]
Additionally:
- [ ] (workaround) Hide for AF before we have translations for Dari and Pashto
- [ ] (R&D) List of languages depending on user admin0pcode

**Comment by pfitzpaddy** [comment]
This is perfect! This will be a great update, nice work @fakhrihawari

**Comment by pfitzpaddy** [comment]
Accidentally closed instead of Comment!

**Comment by pfitzpaddy** [comment]
We could display this for 'COL' only for the time being.... it looks great :)

**Comment by fakhrihawari** [comment]
link to pull request
https://github.com/pfitzpaddy/ngm-reportHub/pull/161
