### ISSUE TITLE
Change download filename for Multi Purpose Cash 

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#19]
Requested to change name from cvwg_... to mpc_...
![chrome_2017-11-08_12-27-58](https://user-images.githubusercontent.com/29349472/32692696-6853636e-c73a-11e7-9104-0a44fec599c4.png)
Currently it takes from $scope.dashboard.cluster_id which is cvwg for cash.

**Comment by drfaustusfade** [comment]
![chrome_2017-11-23_17-45-56](https://user-images.githubusercontent.com/29349472/33175008-dd6cbe20-d077-11e7-8a14-40e7587ef9c9.png)

**Comment by pfitzpaddy** [comment]
Update DEV and PROD
