### ISSUE TITLE
Document Upload to ngmClusterDocuments.js (or something similar)

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#206]
If we place the `uploadDocument`, `manageDocument`, etc in `ngmClusterDocuments.js` as a service we can easily reuse it. https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js#L602

**Comment by fakhrihawari** [comment]
Link pull request
https://github.com/pfitzpaddy/ngm-reportHub/pull/179
