### ISSUE TITLE
Health: add Stock types

### ISSUE THREAD

**Issue by mrecords78** [pfitzpaddy/ngm-reportDesk#21]
The following Stock types needs to be added: RH kit 0, RH kit 1A, RH kit 1B, RH kit 2A, RH kit 2B, RH kit 3, RH kit4, RH kit5, RH kit 6A, RH kit 6B, RH kit 7, RHkit 8, RH kit 9, RH kit 10, RHkit 11A, RHkit 11B, RH kit 12,  Dignity kits, First aid kit, Clean delivery kit, Kitchen kit

**Comment by drfaustusfade** [comment]
**Updated:**


![2017-11-20_16-00-59](https://user-images.githubusercontent.com/29349472/33016417-190636b4-ce0c-11e7-8ad4-67df97be24f1.gif)
