### ISSUE TITLE
Reports Generated Outside Project Dates

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#212]
On the monthly cron scripts (1st of each month), Reports are created for Projects outside of the Project Start Date, End Date. Might be related to previous issue with copy last month (which had incorrect "report_month" etc values).

**Comment by drfaustusfade** [comment]
incorrect generate project reports boundaries 
https://github.com/pfitzpaddy/ngm-reportEngine/pull/109

**Comment by drfaustusfade** [comment]
db update done for af before https://github.com/pfitzpaddy/ngm-reportDesk/issues/214

**Comment by pfitzpaddy** [comment]
Merged https://github.com/pfitzpaddy/ngm-reportEngine/pull/109
