### ISSUE TITLE
Fetch activities list based on ROLE

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#213]
On login, activities are fetched based on the country of registration. This works fine until the user ROLE is REGIONAL or above. i.e. If registered to Afghanistan, when I view Somalia projects the activities are not displayed in the complete monthly activity forms as the base activities list is not available in the system on $filter.

This would be useful for HQ, REGIONAL level ROLEs. NOT important and NOT urgent.

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportEngine/pull/137
https://github.com/pfitzpaddy/ngm-reportHub/pull/297/files

**Comment by pfitzpaddy** [comment]
Nice work @fakhrihawari, thanks, merged.
