### ISSUE TITLE
Add minimize button on each beneficiaries card and search button for beneficiaries list

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#215]
The new form is large. On a long list the page is very long. Following is proposed;

1. Add more information on each Beneficiary card title (i.e. include beneficiary type)
2. Add minimize button, such that the default view is a list (like google docs list). On expand, the form is displayed and rendered (run `ngmClusterBeneficiaries.setBeneficiariesInputs( lists, $parent, $index, beneficiary` );  && `$( 'select' ).material_select()`). This will conflict with the `ng-repeat` limit functionality that is now implemented for locations (it can remain for beneficiaries).
3. Add search button at top of card for keyword and filtering search.

<img width="1056" alt="Screen Shot 2019-06-13 at 10 27 40 am" src="https://user-images.githubusercontent.com/1784705/59404197-72783680-8dc7-11e9-8af3-a3731ad44907.png">

**Comment by fakhrihawari** [comment]
![lkF807wttD](https://user-images.githubusercontent.com/12655589/59481957-d7e42a00-8e90-11e9-84c2-d87d45cabe3a.gif)
![search](https://user-images.githubusercontent.com/12655589/59484924-01578280-8e9e-11e9-8ba8-bdd28883e3e6.png)

**Comment by fakhrihawari** [comment]
Pull Request: https://github.com/pfitzpaddy/ngm-reportHub/pull/225

**Comment by pfitzpaddy** [comment]
Nice work @fakhrihawari. For this feature change, I recommend the following small changes to help guide the user.

1. For `Target Beneficiaries`, the cards are all open by default.
2. For `Monthly Progress Report` beneficiaries, the first beneficiary card (index 0) for each location, is open by default.
3. The title of the card should include `{{ beneficiary.activity_type_name }}, {{ beneficiary.activity_description_name }}, {{ beneficiary.activity_detail_name }}, {{ beneficiary.beneficiary_type_name }}, {{ beneficiary.total }}`
4. `{{ beneficiary.total }}` should be grey colour and right aligned
5. The elements of the form are only activated / rendered on maximise.
6. Include the latest updates from drfaustusfade (select with indexes).

Im sure the styling (points 3 and 4) might require some further review / tweaking as we go along.

Thoughts @fakhrihawari and @drfaustusfade?

**Comment by drfaustusfade** [comment]
all good, in works
7 when card is opened it stays opened ( could be removed to speed up page with less elements to digest )

**Comment by drfaustusfade** [comment]
8. we could consider on click on an entire row, or hover, to ease up user interaction

**Comment by pfitzpaddy** [comment]
For point 8., click on entire row could work (along with the standard click on minimize button as currently stands), the hover option might get a little hectic.

**Comment by drfaustusfade** [comment]
true, then on click and clear tooltip click to expand

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/228

**Comment by fakhrihawari** [comment]
for point 3 If beneficiary.activity_detail_name exist it make the title too long and will look like this
![toolaon](https://user-images.githubusercontent.com/12655589/59672104-15c2b480-91e9-11e9-9cd6-55226bf9f290.PNG)

**Comment by fakhrihawari** [comment]
will fix it

**Comment by fakhrihawari** [comment]
Link pull request for fix:
https://github.com/pfitzpaddy/ngm-reportHub/pull/229

**Comment by pfitzpaddy** [comment]
Merged
