### ISSUE TITLE
CASH Reporting - Modality to “Activity”, “Description” and “Delivery”

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#218]
> Filtering for partner’s cash or voucher data should be based on the “Activity”, “Description” and “Delivery” tabs, so that whenever Cash or Voucher is reported under different clusters, the extract captures them.

If I read correctly, this would propose “Activity”, “Description” and “Delivery” to capture the modality of MPC activities (currently captured under `mpc_delivery_type_id`, `mpc_mechanism_type_id`, `package_type_id`) which requires custom form elements.

FYI - “Activity”, “Description” and “Delivery” where not all available at the time of MPC implementation.

**Comment by drfaustusfade** [comment]
other clusters can have cash activities, mpc need to capture them, that will include mpc_delivery_type_id field, modality is captured by mpc_delivery_type_id and mpc_mechanism_type_id

already resolved with filter on backend if cash cluster:
```
[{ cluster_id: params.cluster_id }, { mpc_purpose_cluster_id: { $regex : params.cluster_id } }, { activity_description_id: { $regex: 'cash' } }, { mpc_delivery_type_id: { $in: ['cash', 'voucher'] } } ] }
```
