### ISSUE TITLE
Health: add to facility type

### ISSUE THREAD

**Issue by mrecords78** [pfitzpaddy/ngm-reportDesk#22]
Add 'Family protection center' and 'Woman friendly health space' to facility type

**Comment by drfaustusfade** [comment]
![2017-11-21_10-28-52](https://user-images.githubusercontent.com/29349472/33057125-e595c952-cea6-11e7-8094-34a1b4772a30.gif)
update on [pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/15)

**Comment by pfitzpaddy** [comment]
Merged, with thanks
