### ISSUE TITLE
In Project List Page, list all projects across cluster / country / region based on user ROLE

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#221]
The Project List page should behave in the same way as the ADMIN page, where the list of Projects and the Admin menu should be based on the user access roles. i.e. Cluster Admin will see all PROJECTS for all ORGANIZATIONS for their SECTOR (menu will display list of Organizations).

![ReportHub_project_list](https://user-images.githubusercontent.com/1784705/60089755-f5ec3d00-9762-11e9-8c7f-66fe58ce0533.png)

**Comment by fakhrihawari** [comment]
Link Pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/265
https://github.com/pfitzpaddy/ngm-reportEngine/pull/127

**Comment by pfitzpaddy** [comment]
Merged
