### ISSUE TITLE
User: Ability to update USER cluster from Profile Page

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#223]
Could include ability to change organization too.

**Comment by fakhrihawari** [comment]
Is it like this?
![Ttrj82lKJ6](https://user-images.githubusercontent.com/12655589/59913597-a47e3e00-9442-11e9-96c5-53c1437a8c57.gif)

**Comment by pfitzpaddy** [comment]
This is great, I suggest the following minor updates;
1. By default, changing Organization for a user profile is disabled;
- The CLUSTER_ADMIN, COUNTRY and COUNTRY_ADMIN only can update an organization for a user.
- The alternative workflow is that the user creates a new log-in with the new organisation and their old account is deactivated / deleted by the old organization.
- The records within saved projects / reports / beneficiaries will remain the same for this user (be they updated, deleted, deactivated), the Project Focal Point will need to be updated from Project Details to update saved projects / reports / beneficiaries.

2. USER, ORG, CLUSTER_ADMIN, COUNTRY and COUNTRY_ADMIN can update their cluster.

3. Have some Toasts on update of ORG and Cluster!

@drfaustusfade, @fakhrihawari, what do you think about the logic for 1 & 2?

**Comment by drfaustusfade** [comment]
Looks good
also notes to consider

proposal to add in api additional flags like for example update: { records: false } to ease up update logic on back end
note for backend implementation  = update organization id on organization change

**Comment by drfaustusfade** [comment]
backend updates https://github.com/pfitzpaddy/ngm-reportEngine/pull/111
id update if organization change ( roles one who updates to be updated on ui for example removing ORG role )
if organization change records will not be updated with user details ( on cluster change will be updated )

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/241

**Comment by drfaustusfade** [comment]
Note: on organization change user organization_id change will be correct if there is one organization by country, if not first registered organisation’s organization_id will be taken
Todo: complete db update one org by country, clean up duplicates

**Comment by pfitzpaddy** [comment]
Merged https://github.com/pfitzpaddy/ngm-reportHub/pull/241
