### ISSUE TITLE
Downloads: Show / Hide Downloads to relevant countries only

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#226]

**Comment by fakhrihawari** [comment]
So just the country of the document and the user country, do we need to consider the ROLE of the user or not?

**Comment by pfitzpaddy** [comment]
For this issue, COUNTRY and / or REGION should be sufficient. The objective is to display downloads that are only applicable for the relevant COUNTRY / REGION, as below;

Nigeria has some custom downloads just for WASH [here](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/dashboards/dashboard.cluster.js#L270)

Afghanistan
- All downloads required but NOT Training download.

Cox's Bazar
- HRP, Stocks, Financial, Training download NOT required.

Colombia
- HRP, Stocks, Training downloads NOT required.

Ethiopia
- HRP, Stocks, Financial downloads NOT required.

Nigeria
- HRP, Stocks, Financial downloads NOT required.

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/242

**Comment by pfitzpaddy** [comment]
Merged
