### ISSUE TITLE
Downloads: Some Admin downloads not working, downloading

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#229]

**Comment by fakhrihawari** [comment]
Is this issue include the download pdf too?

**Comment by drfaustusfade** [comment]
yes, pdf related more to BE, phantomjs v2.0 do not support es6

**Comment by pfitzpaddy** [comment]
I wonder if there is a better way to do this then our current implementation (which seems broken).? Nowadays I’m using screencapture extension for making presentations / graphics from dashboard, since the result is identical to the HTML layout

**Comment by drfaustusfade** [comment]
to fix phantomjs: it should be updated to beta 2.5 version which supports es6, with some fixes around it works, but it is deprecated and better alternative to would be puppeteer
also there are fe libs to take captures in the browser itself combination of html2canvas and jsPDF ( which screen capture seems to use - pdf is made out of png, it will be a bit blurred on zoom, compared to direct pdf export )

**Comment by drfaustusfade** [comment]
init updates to use puppeteer, works for admin and cluster dashboards, for others additional updates to get lists are needed or just implement logging in to fetch all lists:
https://github.com/pfitzpaddy/ngm-reportHub/pull/275
https://github.com/pfitzpaddy/ngm-reportEngine/pull/131
https://github.com/pfitzpaddy/ngm-dashboard-framework/pull/2
note: the same print api, and pdf file by link

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/289

**Comment by pfitzpaddy** [comment]
Merged
