### ISSUE TITLE
Add button for Project Implementation (to separate projects from planned and funded)

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#234]
On the Project Summary page (and perhaps inside the project details form itself), there should be a button to indicate if the project is a Project Plan or Project Implementation. Using "project_status" key, a status if the project could then reflect;
`project_status: new, project_status: plan, project_status: active, project_status: complete, project_status: not_implemented`
- If a project is of type `plan` or `not_implemented`, the reports would not generate.
- When `project_status: plan` is selected, the project start date should automatically update to the current month (except when the `project_status:new`). This can always be later updated by the user.

**Comment by fakhrihawari** [comment]
If the project_status is "plan" or "not_implemented" in project summary page, should we hide the financial report and monthly report or just disabled?
1. hide
![when-project-new](https://user-images.githubusercontent.com/12655589/60410822-4bf23200-9bf4-11e9-8e20-7e5d026b4336.PNG)

2. disabled
![when-project-new2](https://user-images.githubusercontent.com/12655589/60410829-544a6d00-9bf4-11e9-877f-1808841cc816.PNG)

**Comment by pfitzpaddy** [comment]
I like option number 2. Disabled

Can you also switch the order of the "MARK PROJECT AS PLAN" and "MARK PROJECT AS NOT IMPLEMENTED" buttons.

**Comment by fakhrihawari** [comment]
should we separate project by status in project list like this?
![192 168 33 16_desk_](https://user-images.githubusercontent.com/12655589/60422166-9d5ee900-9c15-11e9-8ea6-dfd6f1feedc0.png)

**Comment by pfitzpaddy** [comment]
This is a great idea. I propose;
- Active Projects and Completed Projects are always displayed
- Planned Projects and Not Implemented should not display unless there are records for those categories.

**Comment by fakhrihawari** [comment]
So the default for project_status is not_implemented? because rightnow if we save the project it automatically set project_status to active.

**Comment by pfitzpaddy** [comment]
Let's keep it at active for now. It will be confusing for users if they are required to create a project and then set to active.

**Comment by fakhrihawari** [comment]
Link Pull Request: https://github.com/pfitzpaddy/ngm-reportHub/pull/244

**Comment by pfitzpaddy** [comment]
Merged

**Comment by drfaustusfade** [comment]
when setting plan on an existing project, the start date will jump to the current one, possible situations where the end date will be more then start date, resulting in a bug

**Comment by drfaustusfade** [comment]
some points: 
1 optional proposal: maybe better switch on project creation funded(default)/planned rather than buttons ( less space to confuse users to click for fun ), and maybe have it only in project definition only for the same reason
2 on planned reports generated but with planned status ( and so that filtered later )
3 if then project funded, user change to active on the project cards

**Comment by pfitzpaddy** [comment]
For points above, if I read correctly;
1) We should keep buttons at the bottom of the project, but also add switches at the top of the project too (under details, above donors) in the project definition. Ok to leave or remove from Project Summary page as described.
2) This is a good idea. The challenge then is when they change from Planned to Active, so will the reports, as such it will be impossible to compare Planned vs Actual. Maybe when a project is planned, they should get 3 months of reports ahead of the current date to enter planned activities?

**Comment by pfitzpaddy** [comment]
hmm... what I wrote might add more confusion. I do like the idea of switches at the top, lets add that in and see what it feels like, and then perhaps removing the buttons at the bottom is a good idea indeed.

**Comment by drfaustusfade** [comment]
2. Capturing target beneficiaries in project definition as planned? Or the business case is to capture by month?

**Comment by pfitzpaddy** [comment]
Target Beneficiaries remains as is. There was a request from WASH sector Cox's Bazar and then WASH cluster Nigeria to have 3 month outlook on planned activities by location. This would follow the monthly reporting model. This is not urgent nor an important request, however if we have "Planned" project, we are almost half way there - its just that once the data moves from Planned to Actual there is no historical method to compare the 2 after the change. This topic is just something to think about

**Comment by pfitzpaddy** [comment]
We had an issue or discussion on this monthly planned vs actual, tho I cant find it...

**Comment by drfaustusfade** [comment]
what if project is planned we can add field for beneficiary record if is planned
so in a report there will be both types of records, maybe planned saved in other collection ( plannedbeneficiaries )
update...system generates reports only until this month, needs updates in report generation

**Comment by pfitzpaddy** [comment]
Yes, plannedbeneficiaries is a good idea. From memory, what was propsosed in the issue that I cant find, is that there are 2 cards (planned, actual). You can then "Copy Last Month" or "Copy Planned Month"

**Comment by pfitzpaddy** [comment]
2 cards instead of the current 1 card, "Monthly Progress"
