### ISSUE TITLE
Monthly Report: Beneficiaries form validation (with NG approach)

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#236]
Nigeria uses multiple custom form templates to capture additional 5W information. Each form is implemented with Materialize.
We require similar validation on each Beneficiary card to highlight errors to the user more readily (currently the grey button is causing confusion).
Steps;

1. In [validation helper](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/reports/services/ngmClusterValidation.js), create validateBeneficiaries() function for Monthly Reports (i.e. https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/reports/services/NG/ngmClusterHelperNgWashValidation.js#L879)
2. Enable Save on invalid report
3. Run validateBeneficiaries() similar to [validateBorehole](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/reports/services/NG/ngmClusterHelperNgWashValidation.js#L43) to validate and interactively scroll to errors

**Comment by fakhrihawari** [comment]
![validation](https://user-images.githubusercontent.com/12655589/60640960-d389ac00-9e53-11e9-9d2b-d68645beab59.PNG)
is it enough to just make label red? to show that something wrong in the form

**Comment by pfitzpaddy** [comment]
Looks good. The Red font and **Bold** would be good. Also, the form should scroll to this error in the form (tho i think you probably have this included already).

**Comment by fakhrihawari** [comment]
![e8PyC0xSSD](https://user-images.githubusercontent.com/12655589/60645147-24a09c80-9e62-11e9-98c0-04ad4c2647fd.gif)

**Comment by fakhrihawari** [comment]
Just want to make sure for no 2. is
 Enable Save on invalid report or Unable Save on invalid report?

**Comment by pfitzpaddy** [comment]
What you have in the screencast is perfect. Enable SAVE on invalid report, this will notify and highlight issues to user much easier.

**Comment by fakhrihawari** [comment]
Link Pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/249

**Comment by pfitzpaddy** [comment]
Merged

**Comment by drfaustusfade** [comment]
Open minimized cards with error to scroll to it

**Comment by fakhrihawari** [comment]
Link Pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/255

**Comment by pfitzpaddy** [comment]
Merged
