### ISSUE TITLE
Programme Partner, Implementing Partner Relations & Reporting

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#239]
User workflow to capturing Programme Partner, Implementing Partner relationships;

**Programme Partner**
1. Creates Project
2. Adds Implementing Partner(s), for each Implementing Partner;
3. Creates simplified Project(s) for Implementing Partner within Project Details (title, start date, end date as mandatory - some fields can be taken from Programme Partner project) OR
4. Selects existing project from list of Implementing Partner projects.

**Implementing Partner**
1. Creates Project OR 
2. Completes project already created by Programme Partner (adds / edits / updates default values)
3. Programme Partner field automatically updated by system based on completion of step 2 by Programme Partner, above.

**Comment by drfaustusfade** [comment]
if correct in a project then we need to distinguish programme partner with implementing partner ( to distinguish hierarchy ( implementing partner is sub of programme partner )
also, the question is if an organization needs to specify a partner without hierarchy if such a case.

**Comment by pfitzpaddy** [comment]
Yes on first point. The workflow aims to capture this. For second point, I dont think we need to capture a partner to partner model, as the reporting can be independent (i.e. Partner A is not reporting to Partner B).

**Comment by drfaustusfade** [comment]
in case if Programme Partner creates a project and specifies Implementing Partner that project will be available for Implementing Partner to edit ( also the project is of IP organization or PP? )
but if the case is to capture if organizations just work together?

**Comment by pfitzpaddy** [comment]
Programme Partner will create a project FOR the Implementing Partner to update / edit / report. This way Programme Partner is monitoring, not reporting. Currently IP reports to PP and then PP reports to Cluster. The proposed approach reduces reporting requirements by half. For now I think we should focus on modelling this, as its models humanitarian reporting and has implications on funding and financial tracking. If organizations are just working together then its something we can capture with the existing setup (i.e. use same IDs etc etc), after the initial milestone we can focus on partner to partner relationship

**Comment by pfitzpaddy** [comment]
To enable a basic project submission, we would need to remove most of "required" keys at the model level. Once an IP gets assigned a new project, they can edit and add locations which will generate the monthly reports etc.

**Comment by drfaustusfade** [comment]
Related feature requests
https://github.com/pfitzpaddy/ngm-reportDesk/issues/317
https://github.com/pfitzpaddy/ngm-reportDesk/issues/318
