### ISSUE TITLE
Health: add options under beneficiaries

### ISSUE THREAD

**Issue by mrecords78** [pfitzpaddy/ngm-reportDesk#24]
under "category: d) development" add beneficiary options: 'Health workers' and 'Other beneficiaries'

**Comment by drfaustusfade** [comment]
![2017-11-21_10-28-13](https://user-images.githubusercontent.com/29349472/33057115-dc31ab9c-cea6-11e7-90ca-876e044f8e94.gif)
update on [pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/15)
