### ISSUE TITLE
Project Plan: location slicing remove glitch

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#240]
If deleting not last location, breaks the form
![chrome_2019-06-23_12-05-43](https://user-images.githubusercontent.com/29349472/59974477-dcf85600-95c1-11e9-97d6-05643e54c447.png)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/238

**Comment by pfitzpaddy** [comment]
Merged
