### ISSUE TITLE
Bug(Team): ORG users on team page have All access

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#243]

**Comment by pfitzpaddy** [comment]
I thought we killed this bug. I also noticed that all projects are available when I registered as USER today from the Projects List page. Can be linked to https://github.com/pfitzpaddy/ngm-reportDesk/issues/221

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/240

**Comment by pfitzpaddy** [comment]
Merged
