### ISSUE TITLE
Health: copy or duplicate row button

### ISSUE THREAD

**Issue by mrecords78** [pfitzpaddy/ngm-reportDesk#25]
can we add a "copy row"/"duplicate row" button next to "add row" so that those who need to add many almost identical rows can do it faster? (for example when they need to add many rows where only one category change between each row)

**Comment by drfaustusfade** [comment]
RH has functionality as below, is it not what they need?
![2017-11-20_10-09-54](https://user-images.githubusercontent.com/29349472/33003856-09adbbb4-cddb-11e7-9d94-9d5fd7666b78.gif)

**Comment by pfitzpaddy** [comment]
So for this functionality at least one row must be filled, then it is duplicated from the row before.

**Comment by mrecords78** [comment]
cool, I did not know (and partners also did not know)
has been always like this?

**Comment by pfitzpaddy** [comment]
Yes, but perhaps our training / doc can improve. When you think about it tho, we cant read their mind so they need to give us a chance first :)

**Comment by mrecords78** [comment]
if it has been always like that I have no idea why they ask for it!
ok, next time will double check that they did their homework first
