### ISSUE TITLE
Stocks: Add year filter

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#250]
Just side year filter to get only reports per year, defaulting to the current year
change in route also

**Comment by fakhrihawari** [comment]
Link For Review:
https://github.com/fakhrihawari/ngm-reportHub/tree/year-branch-stock

**Comment by drfaustusfade** [comment]
:thumbsup:
 also organization's createdAt could be used to get year range

**Comment by fakhrihawari** [comment]
okay, I will try to get year range using  organization's createdAt

**Comment by fakhrihawari** [comment]
Can i Make a pull request?

**Comment by fakhrihawari** [comment]
Link Pull Request
https://github.com/pfitzpaddy/ngm-reportHub/pull/302

**Comment by pfitzpaddy** [comment]
Merged
