### ISSUE TITLE
Copy Last Month - Update UI

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#251]
It looks as tho the first beneficiary record is not displayed after performing a Copy Last Month. Please ignore the red circles, this was submitted by one of the partners!

![ICCO JUNE ](https://user-images.githubusercontent.com/1784705/60575503-79c6aa80-9d9d-11e9-847b-7c90971b2af7.jpg)

**Comment by fakhrihawari** [comment]
I think it because beneficiary limit

**Comment by fakhrihawari** [comment]
Link pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/247

**Comment by pfitzpaddy** [comment]
Merged
