### ISSUE TITLE
Custom Deadlines Per Country / Emergency

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#256]
Most countries have custom reporting deadlines. We should include the ability to set this on Project Save / Update, by using a simple object based on admin0pcode in `ProjectController.js` when generating reports.
i.e.
```
var deadline:{
    'AF':{ report_due_date: 5 },
    'CB':{ report_due_date: 7 },
    'ET':{ report_due_date: 7 },
}
```

**Comment by fakhrihawari** [comment]
![z92bjMzF9j](https://user-images.githubusercontent.com/12655589/61101844-90ec5300-a495-11e9-89ae-be8fb00fd415.gif)

**Comment by pfitzpaddy** [comment]
That’s interesting. Perhaps we can have something on the UI which determines the due date. For the time being I was thinking of the object being on the backend in ProjectController.getProjectReports https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/ProjectController.js

**Comment by fakhrihawari** [comment]
okay

**Comment by pfitzpaddy** [comment]
Makes sense to have custom cron jobs for reminders too
```
0 5 8 * * root /home/ubuntu/nginx/www/ngm-reportEngine/tasks/reports/ngm_reporthub_reports_reminder.sh
0 5 12 * * root /home/ubuntu/nginx/www/ngm-reportEngine/tasks/reports/ngm_reporthub_reports_reminder.sh"
```

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportEngine/pull/129
note: cron jobs not altered

**Comment by pfitzpaddy** [comment]
Merged
