### ISSUE TITLE
Custom NGINX 404 Bender page for gulp builds 

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#257]
We are building a lot, we should have an NGINX 404 page as below that attempts a reload every 30 seconds to inform the user ReportHub us updating and to stand by
![404](https://user-images.githubusercontent.com/1784705/61196436-78c44000-a6f0-11e9-8735-12df9b40528b.gif)

**Comment by pfitzpaddy** [comment]
Hey @fakhrihawari, when you have a moment can you please take your maintenance page and make a 403.html page in the same folder. This page will be displayed on `sudo gulp` build. Currently, If a user visits ReportHub when `sudo gulp` is building, the NGINX default 403 page is displayed.

You can use the same style as the maintenance page
<img width="1679" alt="72232546-53a78000-35f4-11ea-8f57-21331867553f" src="https://user-images.githubusercontent.com/1784705/72960193-1488e400-3dd7-11ea-8c5f-026f5a903c2b.png">

**Requirements**: 
- The first line on the bottom of Bender should read "Bender is making some updates!"
- The second line should read "The page will refresh in..."
- The third line should read "30 seconds". `30` should be massive, `seconds` can be smaller.
- The 30 seconds should count down from 30 to 1 seconds
- At 1 second we will want the page to auto refresh to ReportHub home page

**Comment by fakhrihawari** [comment]
okay

**Comment by fakhrihawari** [comment]
version 1
<img width="1680" alt="Screen Shot 2020-01-24 at 14 35 18" src="https://user-images.githubusercontent.com/12655589/73052091-d9f67880-3eb6-11ea-9f2a-399a36bcc77e.png">

version 2
<img width="1680" alt="Screen Shot 2020-01-24 at 14 37 18" src="https://user-images.githubusercontent.com/12655589/73052179-0dd19e00-3eb7-11ea-903a-5ddf4b18075e.png">

**Comment by pfitzpaddy** [comment]
Version 2 is cool, tho I vote for version 1

**Comment by fakhrihawari** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12655589/73149453-17941500-40f4-11ea-987a-81b79c725963.gif)

**Comment by pfitzpaddy** [comment]
Ok, lets merge that one

**Comment by fakhrihawari** [comment]
link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/326

**Comment by pfitzpaddy** [comment]
Merged
