### ISSUE TITLE
Dashboards: Filter caching

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#258]
on pages like project and team when going back from project summary or profile the filter will be reset to a default user role, sometimes a bit inconvenient, some basic caching service could be implemented to remember dashboard paths

**Comment by pfitzpaddy** [comment]
Agreed

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/267

**Comment by pfitzpaddy** [comment]
Merged
