### ISSUE TITLE
Update Menu to Include Submenu (Dropdown Content)

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#260]
Currently, our menu is getting full. We should implement sub menus to save space and group the similar themes of pages.
<img width="214" alt="Screen Shot 2019-07-20 at 11 30 15 am" src="https://user-images.githubusercontent.com/1784705/61574476-1b5e3380-aae2-11e9-8a1f-c0b7be11136a.png">

The drawback is what took 1 click will now take 2, however the logical of the groupings will be an improvement.

**Proposed Groupings**
For each segment that has a dropdown (i.e. Language), include a simple minimise symbol to indicate it contains sub menus.
- Logout
- Language 
    - English
    - Spanish
- My Home (-> click on this item goes to home landing page)
    - My Team
    - My Profile
    - My Admin
    - My Projects
    - My Stocks
- Dashboards (-> click on this item goes to 5W). This will contain the list of dashboard defaults, context specific dashboards can be included in this list here by country / organization.
    - Projects Admin (goes to My Admin)
    - Projects Dashboard
    - 5W Dashboard
- Contact

**Comment by fakhrihawari** [comment]
![BIYnBph4kL](https://user-images.githubusercontent.com/12655589/61614356-b3e4e700-ac8d-11e9-8179-116d6ba07fab.gif)

**Comment by fakhrihawari** [comment]
Link pull request: https://github.com/pfitzpaddy/ngm-reportHub/pull/270

**Comment by pfitzpaddy** [comment]
Merged
