### ISSUE TITLE
Add Search Bar (as in Project Lists) on Team "Active Users" table.

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#261]

**Comment by pfitzpaddy** [comment]
![rh_search](https://user-images.githubusercontent.com/1784705/61610328-a83bf500-ac7a-11e9-9dda-1e69855e2b23.png)

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/272

**Comment by pfitzpaddy** [comment]
Merged
