### ISSUE TITLE
CSS Loading Mask as Project Details Renders

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#262]
As the Project Details is not using directives, there is a lag in the page load time and then the responsiveness of the page / inputs.

A CSS loading mask would be a temp workaround

**Comment by fakhrihawari** [comment]
Demo
https://recordit.co/E0l5nDVCKz

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/273

**Comment by pfitzpaddy** [comment]
Merged
