### ISSUE TITLE
5W Dashboard: Project URL from Leaflet Popup

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#263]
Add the project URL on the 5W dashboard leaflet map popup, click to open in a new window.

**Comment by fakhrihawari** [comment]
![link-to-project-page](https://user-images.githubusercontent.com/12655589/63245442-66f33100-c28a-11e9-9dd7-441b84066032.PNG)
like this?

**Comment by pfitzpaddy** [comment]
Thats perfect, please add PR

**Comment by fakhrihawari** [comment]
Link to Pull Request:
https://github.com/pfitzpaddy/ngm-reportEngine/pull/135

**Comment by pfitzpaddy** [comment]
Merged
