### ISSUE TITLE
Project Details - Minimize Targets on Page Init

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#268]
Some projects are getting big. Propose to minimize Target Beneficiaries and Target Locations once they reach a count limit

- If Target Beneficiaries count is over 30, maximize 1st Target Beneficiary, minimize remaining Target Beneficiaries 
- If Target Locations count is over 30, maximize 1st Target Location, minimize remaining Target Locations

**Comment by pfitzpaddy** [comment]
Sample project (currently loading ok) https://reporthub.immap.org/desk/#/cluster/projects/details/5c9713cd25861c797521ef52

**Comment by fakhrihawari** [comment]
So like this right?
![forngmdesktoptask](https://user-images.githubusercontent.com/12655589/64579263-760e6000-d3ac-11e9-86d2-5a96445fbd05.PNG)

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/296

**Comment by pfitzpaddy** [comment]
Great, thanks - merged
