### ISSUE TITLE
Strategic Objectives in Multi-Cluster Projects are not saved correctly.

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#28]
Saving only for Main Cluster and the last one selected.

**Comment by drfaustusfade** [comment]
solution on [pull request](https://github.com/pfitzpaddy/ngm-reportHub/pull/25)

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD, thanks @drfaustusfade
