### ISSUE TITLE
AF update financial report multi year structure 

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#283]
according to fts reporting template
the field for of amount per year in case of multiyear funding 
![EXCEL_2019-10-11_02-54-14](https://user-images.githubusercontent.com/29349472/66610995-6f088680-ebd2-11e9-9b17-8e745c776749.png)
the form should be adjusted for such functionality

**Comment by fakhrihawari** [comment]
Mock Up
![mockup](https://user-images.githubusercontent.com/12655589/66633647-80cf4580-ec35-11e9-9a15-0a244710a46e.PNG)

**Comment by drfaustusfade** [comment]
> Mock Up
> ![mockup](https://user-images.githubusercontent.com/12655589/66633647-80cf4580-ec35-11e9-9a15-0a244710a46e.PNG)
Thank you!
1. In subform title could be Funding Per Year, and just year on input labels
2. _for year_ column if it is not multiyear
also all multiyear _inputs_ should sum up to _Amount_, years not allocated default to 0, amount of input should be as per project duration
3. If possible to explore a bit leaner/slimmer option: to much space

**Comment by pfitzpaddy** [comment]
Whilst looking at this, is a refactor for Financial Tracking Form to material design a possibility.? Colombia also have a template, so old code could be moved to a Colombia helper (or remain as default)

**Comment by drfaustusfade** [comment]
yes, we can totally migrate to it, as we are updating it now

**Comment by fakhrihawari** [comment]
mock up v2
![mockup2](https://user-images.githubusercontent.com/12655589/66737091-3b10b800-ee95-11e9-915a-9a356b4df1be.PNG)

**Comment by drfaustusfade** [comment]
I would propose also to put received before funds ( ..Currency, Received, Funds, Programming...)
notes could be the entire line as usually takes more space if reported ( in avg 64 char )

**Comment by fakhrihawari** [comment]
Okay

**Comment by fakhrihawari** [comment]
Link Pull Request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/308
https://github.com/pfitzpaddy/ngm-reportEngine/pull/141

**Comment by pfitzpaddy** [comment]
Merged
