### ISSUE TITLE
Upload Monthly Report from xls

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#285]
Processing of uploaded xls file could be done directly on front end, in the same way, copy report functionality is done, but additionally looping through lists ( activities, locations etc ) and adding other _id fields ( report_id, project_id etc) to pick up required __id_ fields, so that the partners will need to specify only _name fields, with the common xls template provided 
.

**Comment by pfitzpaddy** [comment]
@drfaustusfade, FYI I’m currently working on a branch with [js-xlsx](https://github.com/SheetJS/js-xlsx) for ngm-reportEngine. If that’s suitable let’s use the same lib (as I’ve completed XLSX backend work).

**Comment by drfaustusfade** [comment]
yes, this is the lib to use

**Comment by drfaustusfade** [comment]
satellite feature https://github.com/pfitzpaddy/ngm-reportDesk/issues/357

**Comment by drfaustusfade** [comment]
For upcomming open beta version
Basic test cases:
for xlsx, csv, textarea input:
1. it should input by _named fields; template fields as per monthly report download, required columns to be present are so that to match location and activity, and activity required columns
2  it should match and add record by ( admin1,2,3names, sitename, sitetypename, implementationname ) and activity (cluster, type, description, _details_)
3. it should validate if required value is missing or value is present in a not required activity field
4. it should give error message if incorrect value is present
5. it should respect cascading fields filtering
6. it should limit to 1500 rows max

**Comment by fakhrihawari** [comment]
Link Pull Request : 
https://github.com/pfitzpaddy/ngm-reportHub/pull/400
