### ISSUE TITLE
AF Remove SO if project start/end changed year

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#291]
minor bug:
on year update: strategic_objectives not updated, resulting in a further bug

to clean up project
- [x] run script to clean or change start/end year removing and saving a project
```
db.getCollection("project").find({_id: ObjectId("-->>project_id<<--")}).forEach(function(d){

    strategic_objectives_updated = d.strategic_objectives.filter(function(x){return x.objective_year!==2018});
    
    d.strategic_objectives = strategic_objectives_updated;
    
    d.strategic_objectives.forEach(function(e){
   
        print(e.objective_year)

    })
    
    db.getCollection("project").save(d);
    
    });
```

- [x] update fe to remove SO where year is in removed

**Comment by fakhrihawari** [comment]
![Screen Shot 2019-10-24 at 10 24 11](https://user-images.githubusercontent.com/12655589/67450713-802cab00-f648-11e9-83ee-e81357d64700.png)
bug like this?

**Comment by fakhrihawari** [comment]
https://github.com/fakhrihawari/ngm-reportHub/tree/fix-bug-so2

**Comment by fakhrihawari** [comment]
Can i make pull request for this?

**Comment by drfaustusfade** [comment]
on new project if strategic_objectives_check is null it will through error
I think not needed year can be removed on year update, and therefore it will simplify logic a bit

**Comment by pfitzpaddy** [comment]
For Afghanistan, we could move to the approach of having the Strategic / Sector objectives defined in the activities.csv. The issue with this is that it would require some coordination and effort directly with the partners - so im not sure how possible that is. However, for each activity we can define `strategic_objective_id` | `strategic_objective_name` | `strategic_objective_description` | `sector_objective_id` | `sector_objective_name` | `sector_objective_description`. The current implementation of tracking SO is not useable. I mentioned this from the beginning but it was one of the compromises from OCHA to go along with the rollout, to put in the Strategic / Sector objectives. It really adds no value (we dont use it?), unless im mistaken.

**Comment by fakhrihawari** [comment]
link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/316/files

**Comment by pfitzpaddy** [comment]
merged
