### ISSUE TITLE
Dropbox Setting

### ISSUE THREAD

**Issue by Sajatmiko** [pfitzpaddy/ngm-reportDesk#3]
Need your permission to setup dropbox
Detail in attachment.

[reporthub_Dropbox.docx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1320885/reporthub_Dropbox.docx)

**Comment by pfitzpaddy** [comment]
thanks @Sajatmiko, you should now have access. You can close this issue if you do have access

**Comment by Sajatmiko** [comment]
I still not do not be granted to access iMMAP AF Team Folder.

[reporthub_Dropbox_02.docx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1326346/reporthub_Dropbox_02.docx)

**Comment by pfitzpaddy** [comment]
I added access to your iMMAP gmail account. Will add your other email if required.

**Comment by Sajatmiko** [comment]
I used my iMMAP gmail account but still not granted. :(

**Comment by pfitzpaddy** [comment]
Ok, I was unable to update iMMAP AF but I have updated ReportHub folder. Any luck now.?

**Comment by Sajatmiko** [comment]
It works!!! Thank you.
[reporthub_Dropbox_03.docx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1327023/reporthub_Dropbox_03.docx)
