### ISSUE TITLE
Training notes: ESNFI AFG 191217

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#30]
Some points as below, done in 2h, also a couple of minutes were spent on motivating people to be proactive in making proposals and addressing issues:
1. target location in project def: some were asking for countrywide, province selection, or multiple districts in one row, but for the sake of aggregation level it is good as it is, advice was if project is countrywide, to add districts as they need (there is the case where they added every possible district!)
2. For slow internet connection, spin indicator while page loading
3. Distinguish stocks operational stocks and emergency (prepositioned)
4. Month stock report "copy button" functionality from previous month, so that to cut time not adding the same info if it is not much changing from month to month (only numbers)
5. Mute cash related cells for non-cash rows in beneficiaries (already in backlog)

**Comment by drfaustusfade** [comment]
6. More advanced guides needed. As a proposal short thematic by case youtube+screenshots walkthroughs (e.g how to create a new project)

**Comment by pfitzpaddy** [comment]
For item 4) the "copy button", I think thats a good idea. Should this be automated (i.e. previous week is automatically copied with 0's?) or via a button. Where do you think the best place is that we can place that?

**Comment by drfaustusfade** [comment]
item 3. https://github.com/pfitzpaddy/ngm-reportHub/pull/32

**Comment by drfaustusfade** [comment]
item 4. 
- https://github.com/pfitzpaddy/ngm-reportEngine/pull/17
- https://github.com/pfitzpaddy/ngm-reportHub/pull/33

**Comment by drfaustusfade** [comment]
![2018-01-11_18-50-30](https://user-images.githubusercontent.com/29349472/34830093-790b8b64-f700-11e7-8870-c8aa13b5b0a2.gif)

**Comment by drfaustusfade** [comment]
![chrome_2018-01-11_18-53-15](https://user-images.githubusercontent.com/29349472/34830185-b594dd38-f700-11e7-9008-09a1e0ffc9d5.png)
