### ISSUE TITLE
Add new organization (Initiative for Reconstruction and Resettlement) to ReportHub

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#302]
A new organization called Initiative for Reconstruction and Resettlement (IRR) has been submitted by the WASH sector Nigeria to be added to ReportHub. I have already added this organization to the organizations.csv file. Please help update the database with this new record.

**Comment by drfaustusfade** [comment]
Updated

**Comment by dondippino** [comment]
Thank you very much
