### ISSUE TITLE
**URGENT** Save button on Monthly Reporting page clears form on save

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#306]
There is a bug on the Monthly Reporting Page for WASH Nigeria. All entries for beneficiaries on the form are wiped off once the 'Save' button (at the top right of the panel) is clicked for a single activity. We have to give this issue priority as partners are already reporting.

**Comment by drfaustusfade** [comment]
on report save: associations are saved but not populated after create/update resulting in them being empty, as quick workaround, adding findOne with populateAll query after create/update, as update does not have populateAll method, meaning that additional hit on db on each beneficiary...
https://github.com/pfitzpaddy/ngm-reportEngine/pull/157

**Comment by dondippino** [comment]
That is great and thank you for the quick fix. I am thinking of a simpler approach to this issue, I think the 'Save' button at the base of the form persists the precise state of the form at any given time. Hence the 'Save' buttons on the panels might not be needed since the other 'Save' button does the job perfectly.

**Comment by drfaustusfade** [comment]
> That is great and thank you for the quick fix. I am thinking of a simpler approach to this issue, I think the 'Save' button at the base of the form persists the precise state of the form at any given time. Hence the 'Save' buttons on the panels might not be needed since the other 'Save' button does the job perfectly.

It could be an idea to review record level save, then we would need to research into user interactions, but from my experience what I noticed usually users use it heavily
