### ISSUE TITLE
Enable delivery type for WASH sector Nigeria

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#309]
The WASH sector has requested for a field to capture 'Planned' and 'Completed' status of activities. I have implemented something to this effect some months ago and this feature can simply be turned on with the mongo command below:

`db.activities.updateMany({admin0pcode: 'NG',cluster_id: 'wash'}, {$set:{beneficiary_category_type_id: NumberInt(0), beneficiary_delivery_type_id: NumberInt(1)}})`

**Comment by drfaustusfade** [comment]
updated, should activities csv be updated also? 
```
// mongo 3.0.14
db.activities.update({admin0pcode: 'NG',cluster_id: 'wash'}, {$set:{beneficiary_category_type_id: NumberInt(0), beneficiary_delivery_type_id: NumberInt(1)}}, { multi:true });
```

**Comment by dondippino** [comment]
Thank you very much, it works.
