### ISSUE TITLE
Update of Organizations

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#31]
We need to make some minor fixes to the organisations table, as outlined in the attached file
[Double_Organization_tags.xlsx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1582812/Double_Organization_tags.xlsx)

Its important that;
- tab 1, 'doubles': organization_tag should be unique
- tab 2, 'changes':  changes be updated
- tab 3, 'add':  new organizaitons that need to be updated

The existing organization list lives on the Google Drive as you know. Dont need to bother on this until Sunday at earliest.

**Comment by drfaustusfade** [comment]
updated 
notes [Double_Organization_tags_resolved.xlsx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1584856/Double_Organization_tags_resolved.xlsx)

**Comment by opapadak** [comment]
Please change the not "organization_tag" but "organization"

**Comment by pfitzpaddy** [comment]
This is now updated
