### ISSUE TITLE
Update Target Location Interface from xeditable to Forms

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#310]
- [x] update from xeditable to materialize form
- [x] update order of fields, sitetype, implementingsitetype default +depending on activity clusters
- [x] _site from list_ yes/no field depending if adminsites exists, the same logic but should appear or not rather then disabled, so that no need for country condition, and more generalized
- [x] looking for other alternatives to yes/no dropdown, that would look ok on forms

already in works @fakhrihawari 
![ApplicationFrameHost_2020-01-20_13-57-18](https://user-images.githubusercontent.com/29349472/72714741-da2c0680-3b8c-11ea-8e6c-97a693191e1c.png)

to be updated for AF

**Comment by fakhrihawari** [comment]
for old materializecss
https://github.com/fakhrihawari/ngm-reportHub/tree/change-location-in-detail
for materializecss 1x
https://github.com/fakhrihawari/ngm-reportHub/tree/check-error-for-materialize-100

**Comment by fakhrihawari** [comment]
How it will look like:
<img width="1278" alt="Screen Shot 2020-01-21 at 16 38 12" src="https://user-images.githubusercontent.com/12655589/72793017-7e38af00-3c6c-11ea-9aee-751ecace2d13.png">

<img width="1190" alt="Screen Shot 2020-01-21 at 16 39 55" src="https://user-images.githubusercontent.com/12655589/72793155-b04a1100-3c6c-11ea-8d95-47563f455fec.png">

**Comment by pfitzpaddy** [comment]
We will need to test Target Locations for;
- [x] Afghanistan
- [ ] Colombia
- [ ] Ethiopia
- [ ] Somalia
- [ ] Nigeria

Im guessing that the current implementation for Afghanistan is based on the implementation for Cox's Bazar?

**Comment by fakhrihawari** [comment]
Yes

**Comment by pfitzpaddy** [comment]
Nice work. Can you tick off the countries that you deem to be working. Meanwhile I will commit the upgrade to Materialize 1.x today

**Comment by drfaustusfade** [comment]
We were planning to update for AF first, and then others if they test it ok, but they mostly the same, NG has from list selection, which was included, also higher admins, implementation fields based on old ones

**Comment by pfitzpaddy** [comment]
Oh yes, good point. We can commit Afghanistan first with others using old approach until they are tested / moved over....

**Comment by pfitzpaddy** [comment]
If all good for AF, you can make a pull request for the 1.x
