### ISSUE TITLE
Bug in the 'details' feature on the Monthly Reporting form

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#311]
There seems to be a little bug with the 'details' feature on the Monthly Reporting page when there are multiple locations.
When 'details' dropdown is selected for a location, it  clears the selected item in the previous location (if any) and instead switches the select options to the most recent selection.
I have tried to resolve it, but I need other persons' perspective in resolving this.
I have attached a GIF to simulate the scenario perfectly for your comprehension.

**Comment by pfitzpaddy** [comment]
![details_bug_reporthub](https://user-images.githubusercontent.com/1784705/73132899-97b27000-404b-11ea-8289-c2d5329e0f8a.gif)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/328
Proposal:
1 using materialize-select watch
2 initDetails run only on current beneficiaries
3 selects would update on each select change

**Please check and test**
