### ISSUE TITLE
ReportHub - font-color issue on forms 

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#312]
On initial form load, font-color is green, needs to be black.
![ReportHub_font-color_issue](https://user-images.githubusercontent.com/1784705/74145497-2963d500-4c29-11ea-91a8-c3c71c786efc.png)

**Comment by fakhrihawari** [comment]
Ok, I will fix it

**Comment by fakhrihawari** [comment]
link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/342

**Comment by pfitzpaddy** [comment]
Merged
