### ISSUE TITLE
Remove FATP Treatment Same Province from forms

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#313]
![chrome_2020-02-11_15-53-59](https://user-images.githubusercontent.com/29349472/74232779-1a435c80-4ce7-11ea-8601-120dcf031878.png)
- [x] remove treatment same province both beneficiaries and target beneficiaries
- [x] moved to activity details

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/343

**Comment by pfitzpaddy** [comment]
Merged
