### ISSUE TITLE
AF HRP Population types selection

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#315]
by request of OCHA to add common _HRP beneficiary types_ selection in forms for HRP projects, as cluster ones could be different than for hrp, and they prefer selection rather than automatic mapping, even though a bit might be a bit of duplication of effort

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/346
https://github.com/pfitzpaddy/ngm-reportEngine/pull/165

**Comment by pfitzpaddy** [comment]
This is up there with OCHA's request to put SO's and CO's on the Project Plan (instead of them being driven by the data - the Target Beneficiaries activities). A great example of OCHA's total lack of understanding of anything....
