### ISSUE TITLE
AF MPC 2020

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#316]
- unconditional cash interventions, with multi-sectoral objectives under MPC
- sector specific interventions using unconditional cash to meet ONE sectors’ objective under that specific sector

**Comment by drfaustusfade** [comment]
- [x] Remove _Cash intended for_ section as it's not going to be used 
![chrome_2020-02-16_22-54-26](https://user-images.githubusercontent.com/29349472/74610279-69d2bf80-510f-11ea-8934-05d141aed80d.png)

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/348

**Comment by pfitzpaddy** [comment]
Merged

**Comment by drfaustusfade** [comment]
cash form label updates:
**Delivery**: should be changes to:  **Implementation modality**

**Mechanism** to: **Transfer mechanism**
 
_Amount: Please enter the amount per HOUSEHOLD ( HH ) per Transfer_

To be changed to:  _Transfer Value/amount : Please enter the amount per HOUSEHOLD ( HH ) per Transfer_

_Transfers: Please enter the TOTAL number of planned transfers for the ENTIRE project_

To be changed to :

_Number of transfers : Please enter the TOTAL number of planned transfers for the ENTIRE project_
