### ISSUE TITLE
AF Location Implementing Partners Update

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#317]
As programme partners usually report for some implementing partners, request for more granular control on monthly progress; though location-based control on the project plan is mostly enough and covers the case, additional info is needed to be shown on locations with IP, and also requested to be added in location for editing or in beneficiary forms like in interface prototype below(thanks Fakhri); additionally, user permission functionality could be updated to allow access for IP to edit their locations

- [x] functional prototype for IP information on location
- [x] functional prototype for IP selection on location beneficiary 
- [x] on target location IP update, in case of beneficiary input reported beneficiaries implemented partners are not updated and will need to be updated manually
- [x] check for existing bugs, test

<img width="1245" alt="Screen Shot 2020-02-17 at 13 27 32" src="https://user-images.githubusercontent.com/29349472/74738111-da92ec80-5273-11ea-8909-a12a90057fda.png">

**Comment by pfitzpaddy** [comment]
- [x] Display "Implementing Partners" dropdown on Monthly Progress Report IF Project Details is marked as "Programme Partner"?

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportEngine/pull/167
https://github.com/pfitzpaddy/ngm-reportHub/pull/354

**Comment by pfitzpaddy** [comment]
Merged.

**Comment by drfaustusfade** [comment]
The partners cannot handle the logic: project partner > list implementing partners, implementing partners > list programme partner
To keep it simple
Implementing Partners? > list implementing partners, Programme Partners? > list programme partners

**Comment by pfitzpaddy** [comment]
Yes! I agree... thats perfect.

**Comment by pfitzpaddy** [comment]
I will update this now
