### ISSUE TITLE
AF Supporting Organizations

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#318]
As some Implementing partners prefer to report themselves, request to add Supporting Organization (Supporting Partners, Programme Partners ) selection to project definition; usually, it's only one organization, but for corner cases to keep it multiselect as Implementing Partners selection as on interface prototype (thanks Fakhri); common for all project, location, beneficiaries.

- [x] add Programme Partners selection

<img width="1235" alt="Screen Shot 2020-02-18 at 12 27 38" src="https://user-images.githubusercontent.com/29349472/74739881-6a866580-5277-11ea-9f44-1b020fdb7c98.png">

**Comment by pfitzpaddy** [comment]
This is looking good, and a nice and simple solution. A couple of minor proposals below to match the terminology of "Programme Partner" and "Implementing Partner" strictly;

1) In Project Details, provide the option to indicate if the project is either;
- [x] Programme Partner (in which case Implementing Partner drop down becomes available)
- [x] Implementing Partner (in which case Programme Partner drop down becomes available)

2) Include additional column in the Project Details model, for Programme Partners (mathcing Implementing Partners coulm).
i.e. On selection of "Programme Partner";
- [x] "programme_partners" will be added to "project" collection with the following object (to match "implementing_partners")
    - [ ] "adminRpcode"
    - [ ] "adminRname"
    - [ ] "admin0pcode"
    - [ ] "admin0name"
    - [ ] "organization_id"
    - [ ] "organization_tag"
    - [ ] "organization_name"
    - [ ] "organization"
- [x] "implementing_partners" (already included)

3) At "target_location" level and monthly report "beneficiaries" level, further admin tags can be added (not sure if this is relevant, as both "target_location" abd the "beneficiaries" model will already have location information);
i.e. On selection of District Target Location (in addition to the tags above);
- [ ] "admin1pcode"
- [ ] "admin1name"
- [ ] "admin2pcode"
- [ ] "admin2name"

4) Discussion on exports, what tags to parse out for reporting (i.e. add columns programme_partner_id (organization_id), programme_partner_name (organization_name))

**Comment by drfaustusfade** [comment]
Good points, thank you
for 1. to cover cases of intermediate organizations that might have both programme partner and implementing partners, they preferred to have both selections, but one selection would be a cleaner approach

**Comment by pfitzpaddy** [comment]
Yes for 1) we can make that checkbox so both can be selected

**Comment by fakhrihawari** [comment]
Link PR:
pfitzpaddy/ngm-reportEngine#167
pfitzpaddy/ngm-reportHub#354

**Comment by pfitzpaddy** [comment]
Merged

**Comment by pfitzpaddy** [comment]
I dont see `implementing partners` anymore? Did I not load it correctly or has `implementing partners` been removed from Project Details.
<img width="829" alt="Screen Shot 2020-02-20 at 2 16 59 pm" src="https://user-images.githubusercontent.com/1784705/74914276-5d3eb780-53ec-11ea-9cc4-31f6ec8b79c3.png">

In Project Details, partners should have the option of indicating that they are either "Programme Partner" or "Implementing Partner" (or potentially both)

**Comment by pfitzpaddy** [comment]
For the occasions where an `implementing partner` is reporting so they can indicate the Programme Partner(s).

**Comment by drfaustusfade** [comment]
It should be in update

**Comment by fakhrihawari** [comment]
Is it AF project ?

**Comment by pfitzpaddy** [comment]
This is CB project. Option for 1) Programme Partner & 2) Implementing Partner should be default on all project details (Implementing Partner at the location level can be for AF ONLY for time being).

**Comment by fakhrihawari** [comment]
Okay I will put it for All country

**Comment by fakhrihawari** [comment]
link PR for update  :
 https://github.com/pfitzpaddy/ngm-reportHub/pull/355

**Comment by pfitzpaddy** [comment]
Thanks @fakhrihawari. When Programme Partners is selected, can you please update list of Implementing partners to be the same as the dropdown + checkbox style (highlighted in purple square below) that you have implemented for Programme Partner dropdown? 
![reporthub_downdown_select](https://user-images.githubusercontent.com/1784705/74916405-fcb17980-53ef-11ea-8923-6142b2b355a5.png)

It would be consistent and also allows partners to see the options, I like it. Perhaps we could do the same with donor list?

Also, this might open the opportunity to do some cleaning and remove the chips code / library (although im not sure where else the `chips` are used).

**Comment by fakhrihawari** [comment]
Yes, I can make the  List of Implementing partners like Programme Partner dropdown.
And for Donor,  I will try it first and share the mock-up to you all first

**Comment by drfaustusfade** [comment]
With donors it would be alright, but the problem is that users struggle here with typein select interface, so that betters to keep their life easier and use checkboxes for donors, maybe we can add such for donor other option with all other donors

**Comment by pfitzpaddy** [comment]
@drfaustusfade i agree

**Comment by fakhrihawari** [comment]
<img width="1229" alt="Screen Shot 2020-02-21 at 09 08 24" src="https://user-images.githubusercontent.com/12655589/74997903-d7714980-5489-11ea-9e14-caa9b3e88742.png">

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/356
