### ISSUE TITLE
Project Details Load Time

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#320]
Is it just me or does the Project Details sometimes take way too long to load? I think its on the initial loading of that project in a particular session....
![rh_page_load](https://user-images.githubusercontent.com/1784705/75413716-8614fe80-5950-11ea-9e84-bb03f42ce8fa.png)

**Comment by fakhrihawari** [comment]
Yes, I feel the same

**Comment by pfitzpaddy** [comment]
@fakhrihawari can you please take a look when you have time.

**Comment by fakhrihawari** [comment]
From what I read :
https://stackoverflow.com/questions/36764414/slow-performance-with-angular-material-md-select-and-ng-repeat

I think the md-select that made the load slow

**Comment by pfitzpaddy** [comment]
@fakhrihawari could you please see if the solutions listed can get some performance improvements

**Comment by drfaustusfade** [comment]
please check if github.com/pfitzpaddy/ngm-reportHub/pull/363 helps

**Comment by pfitzpaddy** [comment]
I didnt notice much improvement with that PR. It looks as tho the getProject requests do return in a timely fashion - but the mask is not removed.

**Comment by drfaustusfade** [comment]
and this https://github.com/pfitzpaddy/ngm-reportHub/pull/364
this should solve frozen loader when angular not picking up changes

**Comment by pfitzpaddy** [comment]
Im thinking the timing is more consistent now.... it seems.

**Comment by fakhrihawari** [comment]
So now it solved?

**Comment by pfitzpaddy** [comment]
Yes, it looks like it. I will close
