### ISSUE TITLE
Some UI glitches

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#321]
sometimes partners have problems with next which resolves after reload:
to check: 
- [x] after saving project/monthly report next page will have the height of project/monthly report scrolled down
- [x] scroll bar not appearing and page stuck
- [x] very rarely buttons for modals not working
- [x] the login form is stretched out of page on navigation ( try register then login )

**Comment by fakhrihawari** [comment]
For this "after saving project/monthly report next page will have the height of project/monthly report scrolled down" i have it some time . But i still don't know how to recreate this condition to find the bug. Because it is rarely happen

**Comment by drfaustusfade** [comment]
document upload hidden scrollbar on close fix https://github.com/pfitzpaddy/ngm-reportHub/pull/373

**Comment by drfaustusfade** [comment]
- [ ] bug materializecss tooltips break page scrollHeight

**Comment by fakhrihawari** [comment]
> * [ ]  bug materializecss tooltips break page scrollHeight

after click download button?

**Comment by drfaustusfade** [comment]
On project or report pages, hovering on buttons with materialize tooltips, and then, next page will be of that height

**Comment by fakhrihawari** [comment]
* [x]  after download page freeze

**Comment by drfaustusfade** [comment]
removing hanging tooltips from dom on location change https://github.com/pfitzpaddy/ngm-reportHub/pull/374

**Comment by drfaustusfade** [comment]
fix modals on dashboard framework https://github.com/pfitzpaddy/ngm-dashboard-framework/pull/5
