### ISSUE TITLE
AF Project Plan to Activities Plan

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#322]
AF is activities based rather than project-based.
The naming should be updated.
- [x] Project Plan -> Activity Plan (AF)
- [x] Projects -> Activity Plans (AF)

**Comment by pfitzpaddy** [comment]
Thats interesting...

**Comment by fakhrihawari** [comment]
<img width="642" alt="Screen Shot 2020-03-02 at 09 02 46" src="https://user-images.githubusercontent.com/12655589/75639686-a00e5400-5c64-11ea-8749-0b37507a8f26.png">
this one too right?

**Comment by fakhrihawari** [comment]
Link PR: 
https://github.com/pfitzpaddy/ngm-reportHub/pull/369
