### ISSUE TITLE
Bugfix: Unable to select implementation Partner in monthly progress report

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#328]
Implementing partner on the project plan can’t be selected separately in monthly progress report

**Comment by drfaustusfade** [comment]
as for now, implementing partner selection on monthly progress only for AF

**Comment by pfitzpaddy** [comment]
This is now updated for Ethiopia
![rh_implementing_partner](https://user-images.githubusercontent.com/1784705/76421741-b8097480-63d6-11ea-8ec5-2f10814b0671.png)
