### ISSUE TITLE
Bugfix: Do not send notifications to reports already submitted

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#336]
It keeps on sending notification emails for the months the partner has already submitted a report.

**Comment by drfaustusfade** [comment]
there is some mismatch between report_status of reports and locations, as there is a check for locations users
```
db.getCollection("report").find({report_year: 2020, report_month: 0, report_status: "complete"}).forEach(function(d){
    l =  db.getCollection("location").findOne({report_year: 2020, report_month: 0, report_status: "todo", report_id: d._id.valueOf()});
    if (l) print (d.admin0pcode, d._id, l._id);
});
````
could be somewhere problem on location repor_status not overwritten

**Comment by pfitzpaddy** [comment]
This has been resolved
