### ISSUE TITLE
Feature: Enable Stocks module for Ethiopia

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#337]
Partners want to use Stock and pipeline module

**Comment by drfaustusfade** [comment]
currently in works and to be updated today/tomorrow https://github.com/pfitzpaddy/ngm-reportDesk/issues/247

**Comment by pfitzpaddy** [comment]
This is now fixed for ET. I have also updates color scheme!
![ReportHub_stocks](https://user-images.githubusercontent.com/1784705/76599046-b48cff00-6536-11ea-8f46-5179168088eb.png)
