### ISSUE TITLE
Review add location in monthly progress report

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#338]
Has been troublesome in the past

**Comment by fakhrihawari** [comment]
I hope this will solve the problem :
https://github.com/pfitzpaddy/ngm-reportHub/pull/368

**Comment by pfitzpaddy** [comment]
Thanks, thats a good start. I will make some minor tweaks to this.

**Comment by pfitzpaddy** [comment]
Improvement - beneficiaries form is opened by default on "add new location"
<img width="864" alt="et_esnfi_add_location" src="https://user-images.githubusercontent.com/1784705/76397496-bd05fe00-63ad-11ea-9b90-d3ff5695c9ac.png">
