### ISSUE TITLE
Updates to Stock Reports

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#34]
This can be one commit;

1) Update the message when there is no reports from the previous month to be a alert and not an error
![rh_error](https://user-images.githubusercontent.com/1784705/34866622-3c0ad088-f78e-11e7-9e93-1c62d745a300.png)

2) Not to generate Stock Reports per month if there is no warehouse locations for the organisation
![rh_stocks](https://user-images.githubusercontent.com/1784705/34866722-933d5542-f78e-11e7-8d93-ba3ef5f5ef9f.png)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportEngine/pull/21
https://github.com/pfitzpaddy/ngm-reportHub/pull/35

**Comment by drfaustusfade** [comment]
1.![2018-01-12_18-02-58](https://user-images.githubusercontent.com/29349472/34877265-f8027cf8-f7c2-11e7-94d5-b0be07827812.gif)
2. ![2018-01-12_18-03-41](https://user-images.githubusercontent.com/29349472/34877313-2da45548-f7c3-11e7-9d09-41cc30e92350.gif)

**Comment by pfitzpaddy** [comment]
nice & thanks @drfaustusfade
