### ISSUE TITLE
USER rights

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#341]
Currently, regular Users cannot edit projects of other clusters, which is confusing for partners and brings back a lot of questions, as a proposal to allow edit of other cluster projects, or add another type like user per cluster

**Comment by pfitzpaddy** [comment]
It makes sense to open up the rights to enable a user to edit all projects within their org (across each cluster)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/375
