### ISSUE TITLE
AF Disability SADD

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#342]
There is a requirement for this year in AF to have population disaggregated by disability.
As disabled bgmw fields would be the same as bgmw, former bgmw fields can be controlled with the same config for bgmw but conditional per country; as alternative categories could be added to the delivery type
boys_disabled Disabled Boys
girls_disabled Disabled Girls
men_disabled Disabled Men
women_disabled Disabled Women
elderly_men_disabled Disabled Elderly Men
elderly_women_disabled Disabled Elderly Women

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportEngine/pull/172
https://github.com/pfitzpaddy/ngm-reportHub/pull/378

**Comment by pfitzpaddy** [comment]
I would prefer if we do not add additional columns for disabled. We should add them as;
- delivery type "New Beneficiaries, New Beneficiaries (Disabled), etc) 
- or by using the `beneficiary_category_type_id` that was introduced for Colombia. 

The only issue for using `beneficiary_category_type_id` is how to make a "woke" term for not disabled.... "Disabled" and "Not Disabled"? Another long shot is to use `activity_type_detail`, might not be practical.

**Comment by drfaustusfade** [comment]
> I would prefer if we do not add additional columns for disabled. We should add them as;
> 
> * delivery type "New Beneficiaries, New Beneficiaries (Disabled), etc)
> * or by using the `beneficiary_category_type_id` that was introduced for Colombia.
> 
> The only issue for using `beneficiary_category_type_id` is how to make a "woke" term for not disabled.... "Disabled" and "Not Disabled"? Another long shot is to use `activity_type_detail`, might not be practical.

1 _I would prefer if we do not add additional columns for disabled._ Agree, the general notion is to put more prominence on the disabled group, as highlighted for 2020 HRP

2 _New Beneficiaries, New Beneficiaries (Disabled)_ is exactly what we consider as an alternative option

3 _Another long shot is to use `activity_type_detail`, might not be practical._ That's the issue as all activities should have it

4 _or by using the beneficiary_category_type_id that was introduced for Colombia._ exactly what we need, thanks for pointing out, I think we could call it _General_ public and _Disabled_

**Comment by drfaustusfade** [comment]
@fakhrihawari Please proceed with 4 point
- [x] update beneficiary_category_type_id functionality for AF as per 4 point

**Comment by fakhrihawari** [comment]
Link PR :
https://github.com/pfitzpaddy/ngm-reportHub/pull/379

**Comment by pfitzpaddy** [comment]
Merged
