### ISSUE TITLE
Update Stocks to Match Excel Template

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#348]
Update lists of stock items and review

**Comment by pfitzpaddy** [comment]
[Stocks_Pipeline_ESNFI_New Template 2020.xlsx](https://github.com/pfitzpaddy/ngm-reportDesk/files/4352696/Stocks_Pipeline_ESNFI_New.Template.2020.xlsx)

**Comment by drfaustusfade** [comment]
be https://github.com/pfitzpaddy/ngm-reportEngine/pull/181

**Comment by fakhrihawari** [comment]
fe : https://github.com/pfitzpaddy/ngm-reportHub/pull/401

**Comment by pfitzpaddy** [comment]
Merged, with thanks
