### ISSUE TITLE
Add new organization (GLOBAL VILLAGE HEALTHCARE INITIATIVE FOR AFRICA) to ReportHub

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#353]
A new organization called Global Village Healthcare initiative for Africa (GHIV AFRICA) has been submitted by the WASH sector Nigeria to be added to ReportHub. I have already added this organization to the organizations.csv file. Please help update the database with this new record.

**Comment by drfaustusfade** [comment]
updated
