### ISSUE TITLE
Downloads Mouseover Issue

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#354]
The mouse hover is not displaying.
![Screen Shot 2020-04-05 at 4 56 34 pm](https://user-images.githubusercontent.com/1784705/78471889-c1c89280-775e-11ea-82a7-c4f132b37ed5.png)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-dashboard-framework/pull/6

**Comment by fakhrihawari** [comment]
Is it solved?

**Comment by drfaustusfade** [comment]
looks ok
