### ISSUE TITLE
Covid19 reporting support

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#359]
wash cluster af requested in addition to the addition of covid19 activities to add on project and on monthly progress reporting option to specify if an activity is done in response to covid19:
- on project project_details section can be added for additional yes/no project details which could be configured by country (for af factoring out acbar partner option), being array attribute on model
- for monthly progress that's questionable but as an option is to add it to population group, category or vulnerable population, rather than adding an additional field

**Comment by pfitzpaddy** [comment]
In CXB we where going to add COVID19 activities to the activity list, as the COVID19 response activities are a little general.

For AFG, It might be possible to add a 3rd tier of activities i.e. "COVID19 Response", "Routine Activities"? I think the idea to fit it into the current form is a good one, but if all else fails an additional checkbox or so wouldnt be the end of the world either.

**Comment by drfaustusfade** [comment]
3rd tier might fit best for the time being
abstracting from this specific case, to cover requests of such cases with _activity_meta_ information, I am wondering if configurable checkbox fieldset to add prominence or yet another one line multiselect be of value

**Comment by fakhrihawari** [comment]
Link PR for covid19 reporting in Project Detail :
https://github.com/pfitzpaddy/ngm-reportHub/pull/403
https://github.com/pfitzpaddy/ngm-reportEngine/pull/182

<img width="1668" alt="Screen Shot 2020-04-21 at 16 56 39" src="https://user-images.githubusercontent.com/12655589/79852672-28051480-83f1-11ea-91e2-e2f0aa552690.png">

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/427
