### ISSUE TITLE
Investigate and fix createdAt and updatedAt on client when saving collections

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#36]
When a report is saved, it is cleaned, [here](https://github.com/pfitzpaddy/ngm-reportHub/blob/4dfa851d97b7cde66861a86b5428189fd06a6c91/app/scripts/modules/cluster/reports/forms/cluster.project.form.report.js#L926)

During the processing stage in the [ngmClusterHelper service](https://github.com/pfitzpaddy/ngm-reportHub/blob/c0592c13908214e0460e0603b83c90e3e810a3a4/app/scripts/modules/cluster/services/ngmClusterHelper.js#L1402), its looks like the PROJECT `createdAt` and `updatedAt` is overwriting those values for `report + locations + beneficiaries` collections.

This means tracking past updates is essentially useless.

We will need to investigate and fix this. For example, should `createdAt` and `updatedAt` should be removed before merging? Is whats happening already correct and does not need fixing?

Also, latest update will then need to be reviewed in the [reportEngine](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Dashboards/ClusterDashboardController.js#L89)

**Comment by drfaustusfade** [comment]
at pull request https://github.com/pfitzpaddy/ngm-reportHub/pull/40

**Comment by pfitzpaddy** [comment]
Is there any reasonable way to have the beneficiaries record have the correct createdAt / updatedAt values?

**Comment by drfaustusfade** [comment]
yes, so createdAt is fixed, it shows the correct date after fix applied, but for updatedAt looks like waterline update() will always update updatedAt on any document touch.
