### ISSUE TITLE
Update of activities in Education sector - Nigeria on COVID19 response

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#361]
The Education sector in Nigeria has requested that we update ReportHub, with the new activities for COVID19 response.
The csv comprising the new activities have been prepared and added to activities,csv grid online. Kindly help to update the platform with this new data. The CSV file will also be shared with you via Skype.

Best regards

**Comment by drfaustusfade** [comment]
updated
