### ISSUE TITLE
AF cash mpc transfer and grant type fields

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#367]
Additional inputs can be developed (tentative) to complete mpc fieldset:
1 mpc_transfer_type household/individual: some organizations provide per individual, so that amount per household could vary, as a workaround is to put the average amount per household (avg amount times individuals divided by the sum of households)
2 mpc_grant_type as Conditions/Restrictions: to explicitly track the type of cash activities, most are in one to one relation, acting as a meta and should be set automatically, but some could be of selection, for example, _Unconditional, Restricted_ or _Conditional, Restricted_, so far it is put on details
3 calculation on total amount transferred that is _households times transfers times amount_ to monitor total amount

**Comment by fakhrihawari** [comment]
<img width="1181" alt="Screen Shot 2020-06-16 at 10 53 15" src="https://user-images.githubusercontent.com/12655589/84730157-a4fed580-afbf-11ea-9192-7fa0cbab5cd3.png">

Transfers Category(Per Individual / Per Household) => mpc_transfer_type
Grant Type => mpc_grant_type
Total Amount Transfered => total amount transferred

**Comment by drfaustusfade** [comment]
> <img alt="Screen Shot 2020-06-16 at 10 53 15" width="1181" src="https://user-images.githubusercontent.com/12655589/84730157-a4fed580-afbf-11ea-9192-7fa0cbab5cd3.png">
> 
> Transfers Category(Per Individual / Per Household) => mpc_transfer_type
> Grant Type => mpc_grant_type
> Total Amount Transfered => total amount transferred

perfect, some proposal notes: 
- just to keep _Transfer Type_ 
- transfer, grant type row before units row
- total amount disabled for editing, as it is more for self-control, calculation depending on transfer category: if _individual_ then total beneficiaries is taken otherwise _households_ 

notes for backend: 
to add on models grant_type_id, grant_type_name, transfer_category_id, transfer_category_name, total_amount
activities config to add:
array type: mpc_grant_type_id, mpc_transfer_category_id (note: mpc prefix, just to specify fieldset group) 
total_amount could be controlled by mpc_delivery_type_id

**Comment by fakhrihawari** [comment]
<img width="1192" alt="Screen Shot 2020-06-17 at 08 55 27" src="https://user-images.githubusercontent.com/12655589/84846145-56f9d880-b078-11ea-8c69-24ae1e797262.png">
Final

**Comment by fakhrihawari** [comment]
Link PR : 
https://github.com/pfitzpaddy/ngm-reportHub/pull/441
https://github.com/pfitzpaddy/ngm-reportEngine/pull/199

**Comment by pfitzpaddy** [comment]
Merged
