### ISSUE TITLE
GBV Sub Sector Nigeria roll-out implementation and addition of new age groups  

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#371]
The following changes are proposed:
https://github.com/pfitzpaddy/ngm-reportHub/pull/440
https://github.com/pfitzpaddy/ngm-reportEngine/pull/198

These changes are simply to enable CPSS, GBVSS Nigeria and  any other sector to make use of 'sector specific' age-groups which are: boys_0_12, boys_6_12 boys_13_17 and so on.

Changes were made on ngm-reportHub to allow reporting via the sector-specific age groups,
also the download template was updated to allow downloads capture new age groups

On the backend (ngm-reportEngine), download features were implemented to enable accurate downloads for the sector

**Comment by pfitzpaddy** [comment]
Merged
