### ISSUE TITLE
Project Details Loading Time

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#374]
During a workshop / demo yesterday the Project Details took a very long time to load - around about the same time on an empty project as for an existing project. Testing today it seems fine, so im not sure if it was the internet / no. of users, etc. Anyone else noticing this? @fakhrihawari can you take a quick look and see if you can find any obvious bottlenecks on loading?

**Comment by fakhrihawari** [comment]
@pfitzpaddy I try the online version but it seems fine too

**Comment by pfitzpaddy** [comment]
Might be an issue with server load -> multiple requests at the same time...
