### ISSUE TITLE
Form inputs vanishing after submission, not allowing edit

### ISSUE THREAD

**Issue by dondippino** [pfitzpaddy/ngm-reportDesk#376]
![bug_reporthub_28_07_2020](https://user-images.githubusercontent.com/5681166/88705857-014d2d00-d108-11ea-9ddb-d2e8d529b39f.gif)
The select fields in the form for WASH sector in Nigeria vanishes at submission of activities

**Comment by drfaustusfade** [comment]
materialize-select should be added on details' selects 
```
// example
<select materialize-select id="ngm-water_turbidity_range-{{ $locationIndex }}-{{ $beneficiaryIndex }}-{{ $index }}"
	      					name="water_turbidity_range"
	      					class="validate"
```

**Comment by dondippino** [comment]
I have added material-select to all selects in the WASH NG  templates 
here is the PR https://github.com/pfitzpaddy/ngm-reportHub/pull/476
