### ISSUE TITLE
Training notes: Protection AFG 180118

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#40]
Done in 3h, presentation followed by hands-on, 30 people.

1. People tend to use long usernames on registration, we may consider restricting.
2. On mobile registration not working on next button, we may consider disabling some functionality on mobile devices.
3. One user had incorrect system time, it resulted in misfunctioning in functionality on adding project and monthly reporting.
4. For project definition, if backup focal point functionality possible was asked.
5. Data change security question arose, that can be answered by upcoming managing organization teams functionality. 
6. Target beneficiaries in project definition can be templated for monthly reporting; they can be initialized with zeros, so that they always report on what they define, with no need to delete rows.
7. Editing button bug for monthly reports, not appearing in the new year, as it set on condition to be shown for the report year 2017.

**Comment by drfaustusfade** [comment]
lets add **discussion** label

**Comment by pfitzpaddy** [comment]
Maybe those labels can be managed an improved. Also, interested to see the RH presentation. I have one here for Ethiopia. Lets look at how we can share, improve the presentation base so its perfectly consistent

**Comment by pfitzpaddy** [comment]
I use [this one](https://drive.google.com/open?id=1l-ULPkLcg76LA52rOfSELE8WLxNsb5IUGmVtpQ28kK4) (just added some slides now although I think we need a high level presentation and then one in more detail, but lets discuss on our next Skype with Harry).
