### ISSUE TITLE
EPR duplicate lines and wrong SUM

### ISSUE THREAD

**Issue by mrecords78** [pfitzpaddy/ngm-reportDesk#43]
Apparently someone at WHO is still using EPR data from RepHub!!!!!

but when downloading Incidents, the csv has 2 issues (see screenshot):
1) the value of the column 'casualties' is not the sum of casualties over and under 5. Same for 'deaths'
2) there are many lines repeated twice

![image](https://user-images.githubusercontent.com/28835378/35272593-6e7204c4-0053-11e8-9fd2-ada0df925a46.png)

**Comment by pfitzpaddy** [comment]
For the sum, that must be an error [here](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Country/Afg/Epr/EprController.js#L207). For the duplications, this is a work flow that should be managed from th kobo account

**Comment by drfaustusfade** [comment]
pull request on https://github.com/pfitzpaddy/ngm-reportEngine/pull/23

**Comment by drfaustusfade** [comment]
and update to show 2018 in dashboards
https://github.com/pfitzpaddy/ngm-reportHub/pull/42

**Comment by pfitzpaddy** [comment]
Updated on Dev and PROD with thanks!

**Comment by drfaustusfade** [comment]
PROD is not updated
![conemu64_2018-01-29_14-58-06](https://user-images.githubusercontent.com/29349472/35505980-730852ac-0505-11e8-8c61-92df56c5daff.png)

**Comment by drfaustusfade** [comment]
also added routing to 2018 on EPR dashboards opening
https://github.com/pfitzpaddy/ngm-reportHub/pull/43

**Comment by pfitzpaddy** [comment]
There was a conflict on the PROD branch when running update of Engine and Hub

`From https://github.com/pfitzpaddy/ngm-reportEngine
 * branch            master     -> FETCH_HEAD
Updating 4259292..efc04d9
error: Your local changes to the following files would be overwritten by merge:
	api/controllers/Cluster/Reports/ReportTasksController.js
Please, commit your changes or stash them before you can merge.
Aborting`

Now resolved and updated on PROD! Thanks for the re-open ;)
