### ISSUE TITLE
Training Notes: Action Against Hunger Ethiopia

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#44]
ReportHub Training
- Time: January 31, 2018 @ 10:00am
- Organization: Action Against Hunger
- Participants (6)
-- ACF, Yibeltal, Nutrition
-- ACF, Daniel Adugna, WASH
-- ACF, Endale Dlasso Mena, Nutrition
-- ACF, Mahlet Tesfaye, Nutrition
-- ACF, Firehiwot Mezgebu, Nutrition
-- ACF, Temesgen Tamiru, Nutrition 

- [x] 1. feature: Add locations of types "Feeding Centre", "Refugee Camp"
- [x] 2. bug: Error on Target Locations Card (miss aligned headers)
- [x] 3. bug: Profile Page has grey button if Skype name is empty
- [ ] 4. feature: Action Contre la Faim needs to change to Action Against Hunger
- [x] 5. feature: Project Focal Point should receive email notifications (along with Target Location reporting user)
- [ ] 6. feature: Organizations should be able to see projects across all their clusters!
- [x] 7. feature: Amount and Units on all Beneficiary Cards need to be the other way around
- [x] 8. HHs, Units, Amount should not be displaying for Nutrition (could be linked to Agriculture)

**Comment by drfaustusfade** [comment]
5. https://github.com/pfitzpaddy/ngm-reportEngine/issues/25

**Comment by pfitzpaddy** [comment]
6. feature: Organizations should be able to see projects across all their clusters! Still needs investigation
