### ISSUE TITLE
Donor's order

### ISSUE THREAD

**Issue by opapadak** [pfitzpaddy/ngm-reportDesk#48]
You can have 2 different donors, who get in different order in the extract csv from beneficaries or using this link
http://reporthub.immap.org/api/cluster/indicator?adminRpcode=afro&admin0pcode=et&admin1pcode=all&admin2pcode=all&cluster_id=all&organization_tag=all&beneficiaries%5B%5D=all&start_date=2017-01-01&end_date=2018-12-31&csv=true&indicator=beneficiaries&report=all_beneficiary_data&ocha=true

It must be in clicking order but would it be possible to put it in alphabetic order. so that i don't get (donor1,donor2) and (donor2,donor1) as 2 different solutions?

Also I have seen something that looks weird on this project: the front end says WHO and OCHA as donors

HRP Project code is ETH-HRP-2017-HEA-1509518463
![image](https://user-images.githubusercontent.com/4193028/36152220-5063f4b8-10db-11e8-8501-291e95217ede.png)

while the extract says "EHF,OCHA..."

Also OCHA is not a donor, i think it may be deleted from the list

**Comment by pfitzpaddy** [comment]
This is now updated in the following commit https://github.com/pfitzpaddy/ngm-reportEngine/commit/72c6708f0b371974b4027bfe0aedd0e99abe71ed
