### ISSUE TITLE
Cleaning Organization

### ISSUE THREAD

**Issue by opapadak** [pfitzpaddy/ngm-reportDesk#50]
The field "organization" in the organization table (not tag, not name) has some double values
DCA : Dan Church Aid and Dutch Comitee for Afghanistan
FMOH (Ethiopia and Nigeria)
CDC
MSF_Holland

[Double_Organization_tags.xlsx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1724400/Double_Organization_tags.xlsx)

Also you have some organizations Islamic Relief and Islamic Relief for Afghanistan and other where you have the same organization under different names
I already shared this issue in December
Would it be possible to fix this?

**Comment by pfitzpaddy** [comment]
This has been updated in this issue https://github.com/pfitzpaddy/ngm-reportDesk/issues/31
The URL for the latest orgs is [here](http://reporthub.immap.org/api/list/organizations)
