### ISSUE TITLE
Proposal: Open menu icon change

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#54]
For some new users, it could be unclear plus icon to access the menu, so that standard three-line menu icon could be used.

![2018-02-27_12-13-00](https://user-images.githubusercontent.com/29349472/36716901-a256b04c-1bb9-11e8-86ac-81a599040f3e.gif)

vs

![2018-02-27_12-20-38](https://user-images.githubusercontent.com/29349472/36717047-28ed85e0-1bba-11e8-8f55-9ba834d145bc.gif)

Benefits of plus icon are that it is more visually appealing, unique to ReportHub and corresponds to the action.

**Comment by pfitzpaddy** [comment]
Nice, please add pull request and lets get it in there
