### ISSUE TITLE
Add stock report targeted groups selection

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#56]
There is a request from ESNFI for stock reporting to include targeted groups (Natural Disaster, Conflict, Returnee, All population) as some partners are limited to respond to natural disaster affected or returnees or conflict IDPs while others have flexibility for all.

Rolling out in Dev first.

**Comment by pfitzpaddy** [comment]
Merged

**Comment by drfaustusfade** [comment]
- [ ] incorrect condition report.cluster_id === 'esnfi', it should check that if stock row is esnfi then show column, maybe remove it to make targeted groups as non mandatory field for all clusters not only esnfi

**Comment by fakhrihawari** [comment]
pull request 
https://github.com/pfitzpaddy/ngm-reportHub/pull/117

**Comment by pfitzpaddy** [comment]
fix merged
