### ISSUE TITLE
Admin Data Validation Functionality

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#57]
Simple prototype, following today discussion.
![2018-02-28_18-42-12](https://user-images.githubusercontent.com/29349472/36792198-7d4f8afe-1cb7-11e8-8df6-6de6d921f812.gif)
Based on additional admin functionality on report page.
Adding validation field on report, location, and beneficiaries
Opening report from Admin page, downside adminuser needs to open each report, icons on admin page not updated if not reload page, needs websockets etc

**Comment by pfitzpaddy** [comment]
Nice work. I think we can implement that. the cluster IMOs are the only ones to see that right? Also, can you add colors to the buttons -> or perhaps some way to differentiate them from one another. Thank you!

**Comment by drfaustusfade** [comment]
Yes, only for cluster admins and if project submitted.if project edited admin will need to validate again.

**Comment by drfaustusfade** [comment]
Also, there is a thesis, that from a business perspective, more value will be if cluster admin would have the functionality to download cleaned data that s/he sends to ocha

**Comment by pfitzpaddy** [comment]
Added to Project No. 7
