### ISSUE TITLE
Proposal: Additional fields for monthly activity report.

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#6]
There is request as user case for cash activities for monthly activity report download: 
When I extract the monthly report data, I only see the basic information on beneficiary #, date, beneficiary category etc. But I don’t see some of the fields that are listed in the “Target population” section in the “Project Details” page – especially “delivery”, and “transfers”.

**Comment by pfitzpaddy** [comment]
Can you update the monthly activity reports 'api/controllers/Cluster/Reports/ReportController.js' to match those coming from the dashboard 'api/controllers/Cluster/Dashboards/ClusterDashboardController.js', which will include the cash transfer details. Perhaps take a look and see why the monthly report is not using the dashboard export, there must be a reason?

**Comment by drfaustusfade** [comment]
For monthly report:
BE endpoint needs just report_id  to retrieve the report.
So FE sends only those parameters.

On the other hand for dashboard beneficiary download:
BE needs additional parameters cluster_id,  adminR012, organization_tag, beneficiaries, start_date, end_date.

We can modify dashboard api to include report_id, and make corresponding changes to FE, but having separate api, in that case, looks clean enough as it does one thing good, simple, and it could have different fields in future. 

Logically this type of import should follow as for dashboard form, and not if for reporting purposes they need other structure. Cash Transfers and Cash Delivery Type added to export fields.

**Comment by pfitzpaddy** [comment]
Ahh yes good point. The monthly report is only a specific month whereas from the dashboard it can be an aggregation. I agree a seperate API would be an easier and cleaner solution.
