### ISSUE TITLE
Update AF admin 1/2

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#61]
to update collections admin1, admin2
having from new data pcodes and calculated centroids

**Comment by drfaustusfade** [comment]
@pfitzpaddy do we have a google doc for admin1, admin2 config?

**Comment by pfitzpaddy** [comment]
No, and the original scripts I lost somewhere. Thats the bad news. the good news is I imported admin boundaries for Syria  last week, so you can see the scripts in our Dropbox working folder 'ngm > data > scripts > admin'. The `admin.sy.sql` is actually a mix of cmd line and SQL. The first 3 import lines are cmd line, the rest is SQL. Its a little bit manual at the moment, If there is anything in there that is not clear let me know.

**Comment by drfaustusfade** [comment]
nice, there is an issue in updating admin1, admin2; pcodes and centroids changed for AFG, for _Project Target Locations_ in project details as there is filtering by pcode, on its change, existing target location will not be shown
we can update all target_location, locations etc. with new data ( but that means we change reported data )
or we can import new admins without deleting old ones and add _active_ field in admin1 collection to enable filtering for old and new data ```ng-options="item.admin1pcode as item.admin1name for item in project.lists.admin1 | filter:{active: 1}```

**Comment by pfitzpaddy** [comment]
Workaround seems good. Will this have affect on other countries or will they need to be updated to have an active tag?

**Comment by drfaustusfade** [comment]
yes, but we can also add an _inactive_ property to old admin rows, _inactive: true_, and filter:{inactive: '!true'} so that no need to add to everyone

**Comment by pfitzpaddy** [comment]
That seems to be the winner

**Comment by pfitzpaddy** [comment]
This could also be interesting if a partner updated their target location as inactive (maybe due to security situation etc). For now perhaps we don’t need to worry about that.
