### ISSUE TITLE
Add new location types to Afghanistan projects

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#64]
We will need the following 2 new location types added for Afghanistan projects;
- [x] Community Based
- [x] Village

**Comment by pfitzpaddy** [comment]
@drfaustusfade (just struggling to assign this on the mobile)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/69

**Comment by pfitzpaddy** [comment]
Thanks, merged
