### ISSUE TITLE
Add Training Beneficiaries to Dashboard

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#67]
Currently the training beneficiaries from `trainingparticipants` are not counted in the 4W page in the 'Services to Beneficiaries'.

Lets add the `trainingparticipants` to total numbers.

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportEngine/pull/32

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
