### ISSUE TITLE
AF Nutrition weekly reporting

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#69]
Request to implement weekly reporting for nutrition af in the same way EPR and [CDC](https://github.com/iMMAP/cdc-reporting/projects)  is done

**Comment by pfitzpaddy** [comment]
One thing thats been on my todo list for a long time and for future implementations - [kobo URL usr:pwd](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Country/Eth/Ctc/CtcController.js#L34) on api request should be read from a local config file.
