### ISSUE TITLE
Embed youtube tutorial videos 

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#72]
We can embed upcoming youtube tutorial videos on a tutorial page or provide the link to them

**Comment by pfitzpaddy** [comment]
This is a great idea. I think we should not only have a tutorial videos page but also a couple of the videos on the ReportHub splash page. @drfaustusfade, lets include Carlos onto GitHub for the ReportHub repos so we can discuss. One thing that would be really cool - video on PowerQuery / PowerBi integration

**Comment by pfitzpaddy** [comment]
Videos becoming out of date, something to look into. Landing page could do with an overhaul too, [sample](https://ona.io/home/). A longer term objective...
