### ISSUE TITLE
ReportHub User Roles and Accessibility

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#75]
We need to focus on RH user roles, dashboard loading and config for Syria demo with the tasks below;

### User Roles
- [ ] USER filter=[admin0pcode, Organization, Cluster] (can see all team members)
- [ ] ORG filter=[admin0pcode, Organization] - linked to https://github.com/pfitzpaddy/ngm-reportDesk/issues/37 (can see list of all team members and CRUD)
- [ ] CLUSTER filter=[admin0pcode, Cluster] (can see list of all cluster members and CRUD)
- [ ] COUNTRY filter=[admin0pcode]
- [ ] REGION filter=[adminRpcode]
- [ ] SUPERADMIN

**Notes** 
- Currently (USER, ADMIN and SUPERADMIN)

### Admin Dashboard
- [ ] Admin Dashboard access and downloads restricted to the above USER ROLES (i.e. ORG user will see all org projects on admin dashboard across clusters)

### 5W Dashboard
- [ ] 5W Dashboard access and downloads restricted to the above USER ROLES - linked to https://github.com/pfitzpaddy/ngm-reportDesk/issues/74
- [ ] Review [dashboard.cluster.js](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/dashboards/dashboard.cluster.js#L792) init function to improve dashboard requests and loading according to USER ROLES above
- [ ] Review the [ngm-reportEngine apis](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Dashboards/ClusterDashboardController.js) for the dashboard cluster page for any potential benefits
- [ ] Review PDF Print load times at HQ level

### Syria FSAC Activities
- [ ] For Syria, update Activities and Activity Description
[FSS_4Ws_Mastersheet_Jan Actuals_Mar Plans_2018_OCHA.xlsx](https://github.com/pfitzpaddy/ngm-reportDesk/files/1887302/FSS_4Ws_Mastersheet_Jan.Actuals_Mar.Plans_2018_OCHA.xlsx)

**Comment by pfitzpaddy** [comment]
There are no need for updates to Syria.

**Comment by drfaustusfade** [comment]
Global Update Outline: User Management (review)
1. Update roles as per https://github.com/pfitzpaddy/ngm-reportDesk/issues/75 entire app
2. Update notification functionality https://github.com/pfitzpaddy/ngm-reportDesk/issues/100
3. Roles management on UI https://github.com/pfitzpaddy/ngm-reportDesk/issues/100

Note to 1. if updates to db users (review) 
```
1st USERs registered to ORG, leave existing ORG to be
ADMIN to CLUSTER, research functionality for multiple clusters access
SUPERADMIN some to COUNTRY
SUPERADMIN some to SUPERADMIN
```
Note to 3. (review)
```
org admin can grant/take org rights to their org
cluster can grant/take org,cluster rights to their cluster
country can grant/take org,cluster,country rights to their country
region can grant/take org,cluster,country,region rights to their country
superadmin can grant/take org,cluster,country,region, superadmin rights to everyone
```
@fakhrihawari  can start working on it
Also a chance to write down reference regarding roles, and common patterns 
Do we treat roles as increasing in rights hierarchy or each on its own?

**Comment by pfitzpaddy** [comment]
Agreed with above (No. 3 review), looks very good. And the last point you make, a good point to consider. For example, does the cluster meddle with an Org? Something we can discuss.

Latest updates on this, I have just updated the ADMIN page to include a country level admin (for Cox Bazar) within our current setup, whilst we work on a more correct solution outlined above. Results are as follows

`USER: Can see all Projects for all Sectors FOR their ownership Organisation`
<img width="216" alt="user" src="https://user-images.githubusercontent.com/1784705/48203016-7d717100-e377-11e8-8d68-eac6da28c482.png">
'ADMIN: Can see all Projects for all Organisations FOR their ownership Sector'
<img width="222" alt="admin" src="https://user-images.githubusercontent.com/1784705/48203003-75b1cc80-e377-11e8-943f-4c374c1dbf92.png">
'COUNTRY: Can see all Projects for all Organisations for all Sectors FOR their Ownership country'
<img width="219" alt="country" src="https://user-images.githubusercontent.com/1784705/48203218-f7095f00-e377-11e8-9a67-c6d5e879d057.png">
'SUPERADMIN: Can see all Projects for all Organisations for all Sectors for all Countries for all Regions'
<img width="221" alt="region" src="https://user-images.githubusercontent.com/1784705/48203384-6f702000-e378-11e8-98bd-558ccdf0c450.png">

So there are some missing pieces, although point no. 3 in the message above will capture this all very nicely. For point https://github.com/pfitzpaddy/ngm-reportDesk/issues/75, we might consider if USERs are registered across all clusters for their ORG (aposed to a specific cluster, which is what #75 suggest), tying into https://github.com/pfitzpaddy/ngm-reportDesk/issues/98.

@drfaustusfade, can you consider this and if that makes sense, add https://github.com/pfitzpaddy/ngm-reportDesk/issues/98 into your comment above (as an item in the list, taking the list to 4).

**Comment by pfitzpaddy** [comment]
Im pretty sure my last comment is confusing. I should just keep it simple and say - lets include issue https://github.com/pfitzpaddy/ngm-reportDesk/issues/98 in adjustment of USER roles :)

**Comment by pfitzpaddy** [comment]
Added to Project https://github.com/pfitzpaddy/ngm-reportDesk/projects/7
