### ISSUE TITLE
Update AF esnfi reporting logic & activities

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#76]
![2018-04-09_15-16-06](https://user-images.githubusercontent.com/29349472/38493910-21fcebbc-3c09-11e8-8865-29b065d362c1.gif)

https://github.com/pfitzpaddy/ngm-reportHub/pull/79
https://github.com/pfitzpaddy/ngm-reportEngine/pull/33

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
