### ISSUE TITLE
Functionality Not working: Download Monthly Activity Report as CSV.

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#8]
![chrome_2017-10-27_11-26-44](https://user-images.githubusercontent.com/29349472/32091507-be8ab030-bb09-11e7-88a3-fc2a267a4d5b.png)
![conemu64_2017-10-26_17-08-11](https://user-images.githubusercontent.com/29349472/32091525-d6c6a6e0-bb09-11e7-8445-2121b7cde37b.png)

**Comment by pfitzpaddy** [comment]
I cant recreate this somehow, do you have some steps or the page? cheers

**Comment by drfaustusfade** [comment]
Recording on dev server using testcash2 pw test
[screen_recording.zip](https://github.com/pfitzpaddy/ngm-reportDesk/files/1423373/2017-10-28_00-57-20.zip)

**Comment by pfitzpaddy** [comment]
perfect - got it, cheers

**Comment by pfitzpaddy** [comment]
I have removed this download for the time being. I dont think it added value as its was an aggregation of all report values. It would have made more sense to have each beneficiary as a row in the download for the project. Updated on DEV and PROD.
