### ISSUE TITLE
Feature: Admin dashboard filtering by activities

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#80]
Child Protection requested to add activity based filtering for admin dashboard, as a workaround for subcluster implementation. As Admin user they will be able to see all organizations filtered by CPiE activity

**Comment by drfaustusfade** [comment]
Pull requests on:
https://github.com/pfitzpaddy/ngm-reportEngine/pull/37
https://github.com/pfitzpaddy/ngm-reportHub/pull/87
![activity_filter](https://user-images.githubusercontent.com/29349472/41974498-5d23906c-7a2d-11e8-8666-41fe2f9e26b4.png)![cpie_filter](https://user-images.githubusercontent.com/29349472/41974503-61cfa448-7a2d-11e8-9a5a-115bd520cab3.png)
On Protection cluster selection, activity filter is availabe with cpie option.

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
