### ISSUE TITLE
Add Location in Monthly Report

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#86]
For admin0pcode === 'ET' && cluster_id === 'esnfi', we are required to enable users to add a new location directly in a monthly report.

**ngm-reportHub**
1. In views/forms/report/location.html add a new button "Add Location" when admin0pcode === 'ET' && cluster_id === 'esnfi'
2. When selected, a new template adding a new location will appear (e.g. create new template file "cluster/views/forms/report/ET/esnfi/new_location.html")
3. The "Add Location" template will re-use as much HTML and code from the Target Locations template (some attribute name will need to be adjusted) - the form can be simplified and only requires (admin1, admin2, admin3, type, site list?, list, name)
4. On Save Angular will add that location directly to the template list ([locations.html ng-repeat](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/views/forms/report/locations.html#L40))

<img width="965" alt="add_location" src="https://user-images.githubusercontent.com/1784705/45508386-5cd4d280-b79d-11e8-80ff-22a47950b168.png">

**ngm-reportEngine**

5. On report save, the existing setReport should save the new location to the mongodb _Location_ collection. The new location should NOT be saved to _TargetLocation_ mongodb collection - as the location is only required for a single month [api/controllers/Cluster/Reports/setReportById](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Reports/ReportController.js#L491)

**Comment by pfitzpaddy** [comment]
Thanks for the updates, I made some slight modifications as follows;

**ngmEngine Updates**
- https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Reports/ReportController.js#L550 (only code updated apart from adding updateOrCreate in Locations.js model)
- report_status should be updated before save
- lat, lng still required:true in Locations.js and Beneficiaries.js models

**ngmHub Updates**
- https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/views/forms/report/location/new_location.html
- new_location.html template uses all functions from ngmClusterLocations service helper which means admin3 list will now load correctly and new functions not required
- new_location.html will work for all countries (admin1, admin2 and admin3 type_name used in table headings)
- the new functions required are added into [ngmClusterLocations](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/reports/services/ngmClusterLocations.js#L13)
- ngmClusterHelper getCleanReport updated to ensure lat, lng is included before send to server (bit of a tricky one) [here](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/cluster/reports/services/ngmClusterHelper.js#L532)

**Comment by pfitzpaddy** [comment]
For some reason the commit changes for both our code did not show very clearly, but the changes to the code are minimal

**Comment by fakhrihawari** [comment]
Thank you, I learn new thing from your explanation
