### ISSUE TITLE
Materialize update to 1.0.0

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#92]
not before: https://github.com/pfitzpaddy/ngm-reportDesk/issues/91
Open discussion

**Comment by pfitzpaddy** [comment]
@fakhrihawari, can you investigate this issue? From memory, I got stuck at 0.97 because of the modals

**Comment by drfaustusfade** [comment]
https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md

**Comment by fakhrihawari** [comment]
Okay , i will try to investigate it

**Comment by fakhrihawari** [comment]
It is the version should  1.0.0 or the newest one?

**Comment by pfitzpaddy** [comment]
To latest version would be best.

**Comment by fakhrihawari** [comment]
this is what i did to change it materilize 1.0.0
https://github.com/fakhrihawari/ngm-reportHub/tree/move-version-materilize

liitle update for ngm-dashboard-framework 
https://github.com/fakhrihawari/ngm-dashboard-framework

**Comment by fakhrihawari** [comment]
Note: that need to update if we want to move/change to materialize 1.0.0
1. Modal
2. Input checkbox
3 Datepicker
4.floating action for download
5. carousel
6. toast 
7. material_select()

**Comment by pfitzpaddy** [comment]
@fakhrihawari, if possible could you take another look at this, as I have completed the [new module for CXB](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/modules/country/bangladesh/cxb/gfd/app.js) that will also need to go to latest version of Materialize.

There is also a hack for [a modal datepicker](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/scripts/widgets/ngm-table/templates/bgd/gfd/beneficiaries.table.absent.html#L125). Using the new Materialize, it would be far easier to [implement a datepicker](https://materializecss.com/pickers.html), i.e. `var instance = M.Datepicker.getInstance(elem);`

Take a look when possible, sorry for the long delay on this. Let us know if you face any issues on the chat group.

**Comment by fakhrihawari** [comment]
okay I will try to take a look it

**Comment by fakhrihawari** [comment]
like this?
<img width="1648" alt="Screen Shot 2020-01-08 at 11 22 34" src="https://user-images.githubusercontent.com/12655589/71950300-457aed80-3209-11ea-8260-3b02bf385b4b.png">

**Comment by pfitzpaddy** [comment]
perfecto

**Comment by fakhrihawari** [comment]
![demo-datepicker-new (1)](https://user-images.githubusercontent.com/12655589/72034121-bb915a00-32c6-11ea-9c15-cfdeda740836.gif)

https://github.com/fakhrihawari/ngm-reportHub/tree/move-version-materilize

**Comment by pfitzpaddy** [comment]
I have made some minor CSS updates with the new materialize. There are a few minor issues listed below before we update to PROD;
1. When you click on an input (focus) and then click out, the input is given red border-bottom
![rh_css_invalid](https://user-images.githubusercontent.com/1784705/72510884-29b8bc80-3885-11ea-8d66-4ab455f0ca6c.png)
2. Inputs have issue when error. The labels go small and are not displayed red, some inputs should be displayed in red
![rh_css_error](https://user-images.githubusercontent.com/1784705/72510887-2cb3ad00-3885-11ea-8c4a-05971fd32516.png)
3. Please check completed projects, they will also have CSS issues with the disabled styles
![rh_disabled](https://user-images.githubusercontent.com/1784705/72511303-e874dc80-3885-11ea-89a9-85de676283d2.png)
4. The ngm-date datepicker has some issues you know with ngm-dashboard-framework

I had made some CSS updates using the old materialize [here in ngm-form.css](https://github.com/pfitzpaddy/ngm-reportHub/blob/master/app/styles/ngm-form.css#L135-L203), they will need to be reviewed and updated to the new materialize 1.x 

You can use current PROD as an example for input styles / errors.

**Comment by pfitzpaddy** [comment]
This is what a completed project looks like
![rh_css_completed](https://user-images.githubusercontent.com/1784705/72512927-874e0880-3887-11ea-87a9-b78e477c4df7.png)

**Comment by fakhrihawari** [comment]
PR for fix:
https://github.com/pfitzpaddy/ngm-reportHub/pull/323

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
