### ISSUE TITLE
One Organization to Many Clusters

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#98]
Currently, an organization is under cluster, that is one cluster to one organization, as disscussed before proposal is to reverse that relation, so that there is one organization per country, that is one organization to many clusters, which is more logical.

**Comment by pfitzpaddy** [comment]
** Summary **
- [ ] Creating organization detailed [here in User model](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/models/ReportHub/User.js#L211)
- [ ] Updates will be required in ngm-reportHub (i.e. when creating a new project here)
- [ ] Possible links to [User Roles issue here](https://github.com/pfitzpaddy/ngm-reportDesk/issues/75)
- [ ] Good opportunity to add ability of user to select project cluster from popup when "Add New Project"

** Description **
As described, an instance of organization is created based on { admin0pcode, cluster_id, organization }. As such, its possible to have 2 'iMMAPs' for Afghanistan, i.e. 1 for Health and 1 for Nutrition. This is obviously not necessary and a relic of the early days (when RH was Health cluster only) and was enabling an organiation to report on projects across several clusters (but requiring several log-ins).

Currently, if a user is created and the organization for the specified user dosnt exist based on { admin0pcode, cluster_id, organization }, a new one is created to which all the country, cluster, organization projects are mapped. A workaround was implemented many moons ago that added 'organization_tag', for use in the browser and for "cross-sector' organisation queries using this tag. The function for creating [organizations exists here](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/models/ReportHub/User.js#L211). 

This function should be updated to be { admin0pcode, organization } only, with cluster not included / removed.

**NOTE** 
This change to organizations will likely require some changes on the UI (i.e. how project lists are fetched, adding projects and any merging etc) as well as some db updates - potentially some tedious work there. Can be linked to [this issue on user roles](https://github.com/pfitzpaddy/ngm-reportDesk/issues/75). There might be many more such cases required. 

It is also a good opportunity to have a popup that asks the user for which sector they are implementing when they "Add New Project", this way there will not be any need for a user to have 2 log-ins (one for each cluster), which is currently the case! Users cluster will be used as default when creating new and empty project here.

In the end, im not sure how this "feature" has lasted so long :)

**Comment by pfitzpaddy** [comment]
Compiled into Project 7
